// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/consumptionrecord"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/ent/user"
)

// ConsumptionRecord is the model entity for the ConsumptionRecord schema.
type ConsumptionRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// User ID
	UserID int `json:"user_id,omitempty"`
	// Project ID
	ProjectID int `json:"project_id,omitempty"`
	// Model used
	Model string `json:"model,omitempty"`
	// Quota consumed
	Quota int `json:"quota,omitempty"`
	// Trace ID
	TraceID string `json:"trace_id,omitempty"`
	// Prompt tokens
	PromptTokens int `json:"prompt_tokens,omitempty"`
	// Completion tokens
	CompletionTokens int `json:"completion_tokens,omitempty"`
	// Total tokens
	TotalTokens int `json:"total_tokens,omitempty"`
	// Content snippet or hash
	Content string `json:"content,omitempty"`
	// Type of consumption
	Type consumptionrecord.Type `json:"type,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ConsumptionRecordQuery when eager-loading is set.
	Edges        ConsumptionRecordEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ConsumptionRecordEdges holds the relations/edges for other nodes in the graph.
type ConsumptionRecordEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConsumptionRecordEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConsumptionRecordEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ConsumptionRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case consumptionrecord.FieldID, consumptionrecord.FieldUserID, consumptionrecord.FieldProjectID, consumptionrecord.FieldQuota, consumptionrecord.FieldPromptTokens, consumptionrecord.FieldCompletionTokens, consumptionrecord.FieldTotalTokens:
			values[i] = new(sql.NullInt64)
		case consumptionrecord.FieldModel, consumptionrecord.FieldTraceID, consumptionrecord.FieldContent, consumptionrecord.FieldType:
			values[i] = new(sql.NullString)
		case consumptionrecord.FieldCreatedAt, consumptionrecord.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ConsumptionRecord fields.
func (_m *ConsumptionRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case consumptionrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case consumptionrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case consumptionrecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case consumptionrecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case consumptionrecord.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = int(value.Int64)
			}
		case consumptionrecord.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case consumptionrecord.FieldQuota:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quota", values[i])
			} else if value.Valid {
				_m.Quota = int(value.Int64)
			}
		case consumptionrecord.FieldTraceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trace_id", values[i])
			} else if value.Valid {
				_m.TraceID = value.String
			}
		case consumptionrecord.FieldPromptTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prompt_tokens", values[i])
			} else if value.Valid {
				_m.PromptTokens = int(value.Int64)
			}
		case consumptionrecord.FieldCompletionTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field completion_tokens", values[i])
			} else if value.Valid {
				_m.CompletionTokens = int(value.Int64)
			}
		case consumptionrecord.FieldTotalTokens:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_tokens", values[i])
			} else if value.Valid {
				_m.TotalTokens = int(value.Int64)
			}
		case consumptionrecord.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case consumptionrecord.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = consumptionrecord.Type(value.String)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ConsumptionRecord.
// This includes values selected through modifiers, order, etc.
func (_m *ConsumptionRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the ConsumptionRecord entity.
func (_m *ConsumptionRecord) QueryUser() *UserQuery {
	return NewConsumptionRecordClient(_m.config).QueryUser(_m)
}

// QueryProject queries the "project" edge of the ConsumptionRecord entity.
func (_m *ConsumptionRecord) QueryProject() *ProjectQuery {
	return NewConsumptionRecordClient(_m.config).QueryProject(_m)
}

// Update returns a builder for updating this ConsumptionRecord.
// Note that you need to call ConsumptionRecord.Unwrap() before calling this method if this ConsumptionRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ConsumptionRecord) Update() *ConsumptionRecordUpdateOne {
	return NewConsumptionRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ConsumptionRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ConsumptionRecord) Unwrap() *ConsumptionRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ConsumptionRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ConsumptionRecord) String() string {
	var builder strings.Builder
	builder.WriteString("ConsumptionRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("quota=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quota))
	builder.WriteString(", ")
	builder.WriteString("trace_id=")
	builder.WriteString(_m.TraceID)
	builder.WriteString(", ")
	builder.WriteString("prompt_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.PromptTokens))
	builder.WriteString(", ")
	builder.WriteString("completion_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompletionTokens))
	builder.WriteString(", ")
	builder.WriteString("total_tokens=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalTokens))
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteByte(')')
	return builder.String()
}

// ConsumptionRecords is a parsable slice of ConsumptionRecord.
type ConsumptionRecords []*ConsumptionRecord
