// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"

	"github.com/looplj/axonhub/internal/ent/apikey"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/channelmodelprice"
	"github.com/looplj/axonhub/internal/ent/channelmodelpriceversion"
	"github.com/looplj/axonhub/internal/ent/channeloverridetemplate"
	"github.com/looplj/axonhub/internal/ent/channelperformance"
	"github.com/looplj/axonhub/internal/ent/channelprobe"
	"github.com/looplj/axonhub/internal/ent/consumptionrecord"
	"github.com/looplj/axonhub/internal/ent/datastorage"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/ent/prompt"
	"github.com/looplj/axonhub/internal/ent/providerquotastatus"
	"github.com/looplj/axonhub/internal/ent/rechargerecord"
	"github.com/looplj/axonhub/internal/ent/redemptioncode"
	"github.com/looplj/axonhub/internal/ent/request"
	"github.com/looplj/axonhub/internal/ent/requestexecution"
	"github.com/looplj/axonhub/internal/ent/role"
	"github.com/looplj/axonhub/internal/ent/thread"
	"github.com/looplj/axonhub/internal/ent/trace"
	"github.com/looplj/axonhub/internal/ent/usagelog"
	"github.com/looplj/axonhub/internal/ent/user"
	"github.com/looplj/axonhub/internal/ent/userproject"
	"github.com/looplj/axonhub/internal/ent/userrole"
)

// Node in the graph.
type Node struct {
	ID     int      `json:"id,omitempty"`     // node id.
	Type   string   `json:"type,omitempty"`   // node type.
	Fields []*Field `json:"fields,omitempty"` // node fields.
	Edges  []*Edge  `json:"edges,omitempty"`  // node edges.
}

// Field of a node.
type Field struct {
	Type  string `json:"type,omitempty"`  // field type.
	Name  string `json:"name,omitempty"`  // field name (as in struct).
	Value string `json:"value,omitempty"` // stringified value.
}

// Edges between two nodes.
type Edge struct {
	Type string `json:"type,omitempty"` // edge type.
	Name string `json:"name,omitempty"` // edge name.
	IDs  []int  `json:"ids,omitempty"`  // node ids (where this edge point to).
}

// Node implements Noder interface
func (_m *APIKey) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "APIKey",
		Fields: make([]*Field, 12),
		Edges:  make([]*Edge, 4),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UserID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "int",
		Name:  "user_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ProjectID); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "int",
		Name:  "project_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Key); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "key",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Name); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Type); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "apikey.Type",
		Name:  "type",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Status); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "apikey.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Scopes); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "[]string",
		Name:  "scopes",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Profiles); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "*objects.APIKeyProfiles",
		Name:  "profiles",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.IPWhitelist); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "string",
		Name:  "ip_whitelist",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ContentSafetyInterceptEnabled); err != nil {
		return nil, err
	}
	node.Fields[11] = &Field{
		Type:  "bool",
		Name:  "content_safety_intercept_enabled",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "User",
		Name: "user",
	}
	err = _m.QueryUser().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "Project",
		Name: "project",
	}
	err = _m.QueryProject().
		Select(project.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[2] = &Edge{
		Type: "Request",
		Name: "requests",
	}
	err = _m.QueryRequests().
		Select(request.FieldID).
		Scan(ctx, &node.Edges[2].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[3] = &Edge{
		Type: "UsageLog",
		Name: "usage_logs",
	}
	err = _m.QueryUsageLogs().
		Select(usagelog.FieldID).
		Scan(ctx, &node.Edges[3].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *Channel) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "Channel",
		Fields: make([]*Field, 17),
		Edges:  make([]*Edge, 7),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Type); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "channel.Type",
		Name:  "type",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.BaseURL); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "base_url",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Name); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Status); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "channel.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Credentials); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "*objects.ChannelCredentials",
		Name:  "credentials",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.SupportedModels); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "[]string",
		Name:  "supported_models",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.AutoSyncSupportedModels); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "bool",
		Name:  "auto_sync_supported_models",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Tags); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "[]string",
		Name:  "tags",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.DefaultTestModel); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "string",
		Name:  "default_test_model",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Policies); err != nil {
		return nil, err
	}
	node.Fields[11] = &Field{
		Type:  "objects.ChannelPolicies",
		Name:  "policies",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Settings); err != nil {
		return nil, err
	}
	node.Fields[12] = &Field{
		Type:  "*objects.ChannelSettings",
		Name:  "settings",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.OrderingWeight); err != nil {
		return nil, err
	}
	node.Fields[13] = &Field{
		Type:  "int",
		Name:  "ordering_weight",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ErrorMessage); err != nil {
		return nil, err
	}
	node.Fields[14] = &Field{
		Type:  "string",
		Name:  "error_message",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Remark); err != nil {
		return nil, err
	}
	node.Fields[15] = &Field{
		Type:  "string",
		Name:  "remark",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Group); err != nil {
		return nil, err
	}
	node.Fields[16] = &Field{
		Type:  "string",
		Name:  "group",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "Request",
		Name: "requests",
	}
	err = _m.QueryRequests().
		Select(request.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "RequestExecution",
		Name: "executions",
	}
	err = _m.QueryExecutions().
		Select(requestexecution.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[2] = &Edge{
		Type: "UsageLog",
		Name: "usage_logs",
	}
	err = _m.QueryUsageLogs().
		Select(usagelog.FieldID).
		Scan(ctx, &node.Edges[2].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[3] = &Edge{
		Type: "ChannelPerformance",
		Name: "channel_performance",
	}
	err = _m.QueryChannelPerformance().
		Select(channelperformance.FieldID).
		Scan(ctx, &node.Edges[3].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[4] = &Edge{
		Type: "ChannelProbe",
		Name: "channel_probes",
	}
	err = _m.QueryChannelProbes().
		Select(channelprobe.FieldID).
		Scan(ctx, &node.Edges[4].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[5] = &Edge{
		Type: "ChannelModelPrice",
		Name: "channel_model_prices",
	}
	err = _m.QueryChannelModelPrices().
		Select(channelmodelprice.FieldID).
		Scan(ctx, &node.Edges[5].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[6] = &Edge{
		Type: "ProviderQuotaStatus",
		Name: "provider_quota_status",
	}
	err = _m.QueryProviderQuotaStatus().
		Select(providerquotastatus.FieldID).
		Scan(ctx, &node.Edges[6].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *ChannelModelPrice) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "ChannelModelPrice",
		Fields: make([]*Field, 6),
		Edges:  make([]*Edge, 2),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ChannelID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "int",
		Name:  "channel_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ModelID); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "model_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Price); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "objects.ModelPrice",
		Name:  "price",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ReferenceID); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "string",
		Name:  "reference_id",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "Channel",
		Name: "channel",
	}
	err = _m.QueryChannel().
		Select(channel.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "ChannelModelPriceVersion",
		Name: "versions",
	}
	err = _m.QueryVersions().
		Select(channelmodelpriceversion.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *ChannelModelPriceVersion) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "ChannelModelPriceVersion",
		Fields: make([]*Field, 10),
		Edges:  make([]*Edge, 1),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ChannelID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "int",
		Name:  "channel_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ModelID); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "model_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ChannelModelPriceID); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "int",
		Name:  "channel_model_price_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Price); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "objects.ModelPrice",
		Name:  "price",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Status); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "channelmodelpriceversion.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.EffectiveStartAt); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "time.Time",
		Name:  "effective_start_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.EffectiveEndAt); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "time.Time",
		Name:  "effective_end_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ReferenceID); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "string",
		Name:  "reference_id",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "ChannelModelPrice",
		Name: "channel_model_price",
	}
	err = _m.QueryChannelModelPrice().
		Select(channelmodelprice.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *ChannelOverrideTemplate) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "ChannelOverrideTemplate",
		Fields: make([]*Field, 8),
		Edges:  make([]*Edge, 1),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UserID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "int",
		Name:  "user_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Name); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Description); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "description",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ChannelType); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "string",
		Name:  "channel_type",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.OverrideParameters); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "string",
		Name:  "override_parameters",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.OverrideHeaders); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "[]objects.HeaderEntry",
		Name:  "override_headers",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "User",
		Name: "user",
	}
	err = _m.QueryUser().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *ChannelPerformance) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "ChannelPerformance",
		Fields: make([]*Field, 21),
		Edges:  make([]*Edge, 1),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ChannelID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "int",
		Name:  "channel_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.SuccessRate); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "int",
		Name:  "success_rate",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.AvgLatencyMs); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "int",
		Name:  "avg_latency_ms",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.AvgTokenPerSecond); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "int",
		Name:  "avg_token_per_second",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.AvgStreamFirstTokenLatencyMs); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "int",
		Name:  "avg_stream_first_token_latency_ms",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.AvgStreamTokenPerSecond); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "float64",
		Name:  "avg_stream_token_per_second",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.LastSuccessAt); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "time.Time",
		Name:  "last_success_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.LastFailureAt); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "time.Time",
		Name:  "last_failure_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.RequestCount); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "int64",
		Name:  "request_count",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.SuccessCount); err != nil {
		return nil, err
	}
	node.Fields[11] = &Field{
		Type:  "int64",
		Name:  "success_count",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.FailureCount); err != nil {
		return nil, err
	}
	node.Fields[12] = &Field{
		Type:  "int64",
		Name:  "failure_count",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.TotalTokenCount); err != nil {
		return nil, err
	}
	node.Fields[13] = &Field{
		Type:  "int64",
		Name:  "total_token_count",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.TotalRequestLatencyMs); err != nil {
		return nil, err
	}
	node.Fields[14] = &Field{
		Type:  "int64",
		Name:  "total_request_latency_ms",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.StreamSuccessCount); err != nil {
		return nil, err
	}
	node.Fields[15] = &Field{
		Type:  "int64",
		Name:  "stream_success_count",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.StreamTotalRequestCount); err != nil {
		return nil, err
	}
	node.Fields[16] = &Field{
		Type:  "int64",
		Name:  "stream_total_request_count",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.StreamTotalTokenCount); err != nil {
		return nil, err
	}
	node.Fields[17] = &Field{
		Type:  "int64",
		Name:  "stream_total_token_count",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.StreamTotalRequestLatencyMs); err != nil {
		return nil, err
	}
	node.Fields[18] = &Field{
		Type:  "int64",
		Name:  "stream_total_request_latency_ms",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.StreamTotalFirstTokenLatencyMs); err != nil {
		return nil, err
	}
	node.Fields[19] = &Field{
		Type:  "int64",
		Name:  "stream_total_first_token_latency_ms",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ConsecutiveFailures); err != nil {
		return nil, err
	}
	node.Fields[20] = &Field{
		Type:  "int64",
		Name:  "consecutive_failures",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "Channel",
		Name: "channel",
	}
	err = _m.QueryChannel().
		Select(channel.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *ChannelProbe) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "ChannelProbe",
		Fields: make([]*Field, 4),
		Edges:  make([]*Edge, 1),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.ChannelID); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "int",
		Name:  "channel_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.TotalRequestCount); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "int",
		Name:  "total_request_count",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.SuccessRequestCount); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "int",
		Name:  "success_request_count",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Timestamp); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "int64",
		Name:  "timestamp",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "Channel",
		Name: "channel",
	}
	err = _m.QueryChannel().
		Select(channel.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *ConsumptionRecord) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "ConsumptionRecord",
		Fields: make([]*Field, 12),
		Edges:  make([]*Edge, 2),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UserID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "int",
		Name:  "user_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ProjectID); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "int",
		Name:  "project_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Model); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "model",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Quota); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "int",
		Name:  "quota",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.TraceID); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "string",
		Name:  "trace_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.PromptTokens); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "int",
		Name:  "prompt_tokens",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.CompletionTokens); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "int",
		Name:  "completion_tokens",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.TotalTokens); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "int",
		Name:  "total_tokens",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Content); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "string",
		Name:  "content",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Type); err != nil {
		return nil, err
	}
	node.Fields[11] = &Field{
		Type:  "consumptionrecord.Type",
		Name:  "type",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "User",
		Name: "user",
	}
	err = _m.QueryUser().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "Project",
		Name: "project",
	}
	err = _m.QueryProject().
		Select(project.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *DataStorage) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "DataStorage",
		Fields: make([]*Field, 8),
		Edges:  make([]*Edge, 2),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Name); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Description); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "description",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Primary); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "bool",
		Name:  "primary",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Type); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "datastorage.Type",
		Name:  "type",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Settings); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "*objects.DataStorageSettings",
		Name:  "settings",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Status); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "datastorage.Status",
		Name:  "status",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "Request",
		Name: "requests",
	}
	err = _m.QueryRequests().
		Select(request.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "RequestExecution",
		Name: "executions",
	}
	err = _m.QueryExecutions().
		Select(requestexecution.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *Model) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "Model",
		Fields: make([]*Field, 12),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Developer); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "developer",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ModelID); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "model_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Type); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "model.Type",
		Name:  "type",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Name); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Icon); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "string",
		Name:  "icon",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Group); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "string",
		Name:  "group",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ModelCard); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "*objects.ModelCard",
		Name:  "model_card",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Settings); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "*objects.ModelSettings",
		Name:  "settings",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Status); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "model.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Remark); err != nil {
		return nil, err
	}
	node.Fields[11] = &Field{
		Type:  "string",
		Name:  "remark",
		Value: string(buf),
	}
	return node, nil
}

// Node implements Noder interface
func (_m *ModelPricing) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "ModelPricing",
		Fields: make([]*Field, 8),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Model); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "model",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Type); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "modelpricing.Type",
		Name:  "type",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Status); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "modelpricing.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Quota); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "float64",
		Name:  "quota",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.CompletionRatio); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "float64",
		Name:  "completion_ratio",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Price); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "float64",
		Name:  "price",
		Value: string(buf),
	}
	return node, nil
}

// Node implements Noder interface
func (_m *Project) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "Project",
		Fields: make([]*Field, 8),
		Edges:  make([]*Edge, 11),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Name); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Description); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "description",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Status); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "project.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Quota); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "int64",
		Name:  "quota",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UsedQuota); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "int64",
		Name:  "used_quota",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Group); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "string",
		Name:  "group",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "User",
		Name: "users",
	}
	err = _m.QueryUsers().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "Role",
		Name: "roles",
	}
	err = _m.QueryRoles().
		Select(role.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[2] = &Edge{
		Type: "APIKey",
		Name: "api_keys",
	}
	err = _m.QueryAPIKeys().
		Select(apikey.FieldID).
		Scan(ctx, &node.Edges[2].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[3] = &Edge{
		Type: "Request",
		Name: "requests",
	}
	err = _m.QueryRequests().
		Select(request.FieldID).
		Scan(ctx, &node.Edges[3].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[4] = &Edge{
		Type: "UsageLog",
		Name: "usage_logs",
	}
	err = _m.QueryUsageLogs().
		Select(usagelog.FieldID).
		Scan(ctx, &node.Edges[4].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[5] = &Edge{
		Type: "Thread",
		Name: "threads",
	}
	err = _m.QueryThreads().
		Select(thread.FieldID).
		Scan(ctx, &node.Edges[5].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[6] = &Edge{
		Type: "Trace",
		Name: "traces",
	}
	err = _m.QueryTraces().
		Select(trace.FieldID).
		Scan(ctx, &node.Edges[6].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[7] = &Edge{
		Type: "Prompt",
		Name: "prompts",
	}
	err = _m.QueryPrompts().
		Select(prompt.FieldID).
		Scan(ctx, &node.Edges[7].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[8] = &Edge{
		Type: "ConsumptionRecord",
		Name: "consumption_records",
	}
	err = _m.QueryConsumptionRecords().
		Select(consumptionrecord.FieldID).
		Scan(ctx, &node.Edges[8].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[9] = &Edge{
		Type: "RechargeRecord",
		Name: "recharge_records",
	}
	err = _m.QueryRechargeRecords().
		Select(rechargerecord.FieldID).
		Scan(ctx, &node.Edges[9].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[10] = &Edge{
		Type: "UserProject",
		Name: "project_users",
	}
	err = _m.QueryProjectUsers().
		Select(userproject.FieldID).
		Scan(ctx, &node.Edges[10].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *Prompt) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "Prompt",
		Fields: make([]*Field, 9),
		Edges:  make([]*Edge, 1),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ProjectID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "int",
		Name:  "project_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Name); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Description); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "description",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Role); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "string",
		Name:  "role",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Content); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "string",
		Name:  "content",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Status); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "prompt.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Settings); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "objects.PromptSettings",
		Name:  "settings",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "Project",
		Name: "projects",
	}
	err = _m.QueryProjects().
		Select(project.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *ProviderQuotaStatus) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "ProviderQuotaStatus",
		Fields: make([]*Field, 9),
		Edges:  make([]*Edge, 1),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ChannelID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "int",
		Name:  "channel_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ProviderType); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "providerquotastatus.ProviderType",
		Name:  "provider_type",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Status); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "providerquotastatus.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.QuotaData); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "map[string]interface {}",
		Name:  "quota_data",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.NextResetAt); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "time.Time",
		Name:  "next_reset_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Ready); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "bool",
		Name:  "ready",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.NextCheckAt); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "time.Time",
		Name:  "next_check_at",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "Channel",
		Name: "channel",
	}
	err = _m.QueryChannel().
		Select(channel.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *RechargeRecord) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "RechargeRecord",
		Fields: make([]*Field, 8),
		Edges:  make([]*Edge, 3),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UserID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "int",
		Name:  "user_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ProjectID); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "int",
		Name:  "project_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.CodeID); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "int",
		Name:  "code_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Amount); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "int64",
		Name:  "amount",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Status); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "rechargerecord.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.TraceID); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "string",
		Name:  "trace_id",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "User",
		Name: "user",
	}
	err = _m.QueryUser().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "Project",
		Name: "project",
	}
	err = _m.QueryProject().
		Select(project.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[2] = &Edge{
		Type: "RedemptionCode",
		Name: "redemption_code",
	}
	err = _m.QueryRedemptionCode().
		Select(redemptioncode.FieldID).
		Scan(ctx, &node.Edges[2].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *RedemptionCode) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "RedemptionCode",
		Fields: make([]*Field, 11),
		Edges:  make([]*Edge, 2),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Code); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "code",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Quota); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "int",
		Name:  "quota",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Status); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "redemptioncode.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ExpiresAt); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "time.Time",
		Name:  "expires_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.MaxUses); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "int",
		Name:  "max_uses",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UsedTimes); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "int",
		Name:  "used_times",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Voided); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "bool",
		Name:  "voided",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UsedBy); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "int",
		Name:  "used_by",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UsedAt); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "time.Time",
		Name:  "used_at",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "User",
		Name: "user",
	}
	err = _m.QueryUser().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "RechargeRecord",
		Name: "recharge_records",
	}
	err = _m.QueryRechargeRecords().
		Select(rechargerecord.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *Request) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "Request",
		Fields: make([]*Field, 20),
		Edges:  make([]*Edge, 7),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.APIKeyID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "int",
		Name:  "api_key_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ProjectID); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "int",
		Name:  "project_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.TraceID); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "int",
		Name:  "trace_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.DataStorageID); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "int",
		Name:  "data_storage_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Source); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "request.Source",
		Name:  "source",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ModelID); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "string",
		Name:  "model_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Format); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "string",
		Name:  "format",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.RequestHeaders); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "objects.JSONRawMessage",
		Name:  "request_headers",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.RequestBody); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "objects.JSONRawMessage",
		Name:  "request_body",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ResponseBody); err != nil {
		return nil, err
	}
	node.Fields[11] = &Field{
		Type:  "objects.JSONRawMessage",
		Name:  "response_body",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ResponseChunks); err != nil {
		return nil, err
	}
	node.Fields[12] = &Field{
		Type:  "[]objects.JSONRawMessage",
		Name:  "response_chunks",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ChannelID); err != nil {
		return nil, err
	}
	node.Fields[13] = &Field{
		Type:  "int",
		Name:  "channel_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ExternalID); err != nil {
		return nil, err
	}
	node.Fields[14] = &Field{
		Type:  "string",
		Name:  "external_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Status); err != nil {
		return nil, err
	}
	node.Fields[15] = &Field{
		Type:  "request.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Stream); err != nil {
		return nil, err
	}
	node.Fields[16] = &Field{
		Type:  "bool",
		Name:  "stream",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ClientIP); err != nil {
		return nil, err
	}
	node.Fields[17] = &Field{
		Type:  "string",
		Name:  "client_ip",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.MetricsLatencyMs); err != nil {
		return nil, err
	}
	node.Fields[18] = &Field{
		Type:  "int64",
		Name:  "metrics_latency_ms",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.MetricsFirstTokenLatencyMs); err != nil {
		return nil, err
	}
	node.Fields[19] = &Field{
		Type:  "int64",
		Name:  "metrics_first_token_latency_ms",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "APIKey",
		Name: "api_key",
	}
	err = _m.QueryAPIKey().
		Select(apikey.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "Project",
		Name: "project",
	}
	err = _m.QueryProject().
		Select(project.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[2] = &Edge{
		Type: "Trace",
		Name: "trace",
	}
	err = _m.QueryTrace().
		Select(trace.FieldID).
		Scan(ctx, &node.Edges[2].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[3] = &Edge{
		Type: "DataStorage",
		Name: "data_storage",
	}
	err = _m.QueryDataStorage().
		Select(datastorage.FieldID).
		Scan(ctx, &node.Edges[3].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[4] = &Edge{
		Type: "RequestExecution",
		Name: "executions",
	}
	err = _m.QueryExecutions().
		Select(requestexecution.FieldID).
		Scan(ctx, &node.Edges[4].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[5] = &Edge{
		Type: "Channel",
		Name: "channel",
	}
	err = _m.QueryChannel().
		Select(channel.FieldID).
		Scan(ctx, &node.Edges[5].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[6] = &Edge{
		Type: "UsageLog",
		Name: "usage_logs",
	}
	err = _m.QueryUsageLogs().
		Select(usagelog.FieldID).
		Scan(ctx, &node.Edges[6].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *RequestExecution) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "RequestExecution",
		Fields: make([]*Field, 18),
		Edges:  make([]*Edge, 3),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ProjectID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "int",
		Name:  "project_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.RequestID); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "int",
		Name:  "request_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ChannelID); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "int",
		Name:  "channel_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.DataStorageID); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "int",
		Name:  "data_storage_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ExternalID); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "string",
		Name:  "external_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ModelID); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "string",
		Name:  "model_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Format); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "string",
		Name:  "format",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.RequestBody); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "objects.JSONRawMessage",
		Name:  "request_body",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ResponseBody); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "objects.JSONRawMessage",
		Name:  "response_body",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ResponseChunks); err != nil {
		return nil, err
	}
	node.Fields[11] = &Field{
		Type:  "[]objects.JSONRawMessage",
		Name:  "response_chunks",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ErrorMessage); err != nil {
		return nil, err
	}
	node.Fields[12] = &Field{
		Type:  "string",
		Name:  "error_message",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Status); err != nil {
		return nil, err
	}
	node.Fields[13] = &Field{
		Type:  "requestexecution.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Stream); err != nil {
		return nil, err
	}
	node.Fields[14] = &Field{
		Type:  "bool",
		Name:  "stream",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.MetricsLatencyMs); err != nil {
		return nil, err
	}
	node.Fields[15] = &Field{
		Type:  "int64",
		Name:  "metrics_latency_ms",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.MetricsFirstTokenLatencyMs); err != nil {
		return nil, err
	}
	node.Fields[16] = &Field{
		Type:  "int64",
		Name:  "metrics_first_token_latency_ms",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.RequestHeaders); err != nil {
		return nil, err
	}
	node.Fields[17] = &Field{
		Type:  "objects.JSONRawMessage",
		Name:  "request_headers",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "Request",
		Name: "request",
	}
	err = _m.QueryRequest().
		Select(request.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "Channel",
		Name: "channel",
	}
	err = _m.QueryChannel().
		Select(channel.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[2] = &Edge{
		Type: "DataStorage",
		Name: "data_storage",
	}
	err = _m.QueryDataStorage().
		Select(datastorage.FieldID).
		Scan(ctx, &node.Edges[2].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *Role) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "Role",
		Fields: make([]*Field, 6),
		Edges:  make([]*Edge, 3),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Name); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Level); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "role.Level",
		Name:  "level",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ProjectID); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "int",
		Name:  "project_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Scopes); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "[]string",
		Name:  "scopes",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "User",
		Name: "users",
	}
	err = _m.QueryUsers().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "Project",
		Name: "project",
	}
	err = _m.QueryProject().
		Select(project.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[2] = &Edge{
		Type: "UserRole",
		Name: "user_roles",
	}
	err = _m.QueryUserRoles().
		Select(userrole.FieldID).
		Scan(ctx, &node.Edges[2].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *SensitiveWord) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "SensitiveWord",
		Fields: make([]*Field, 4),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Word); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "word",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Type); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "sensitiveword.Type",
		Name:  "type",
		Value: string(buf),
	}
	return node, nil
}

// Node implements Noder interface
func (_m *System) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "System",
		Fields: make([]*Field, 4),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Key); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "key",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Value); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "value",
		Value: string(buf),
	}
	return node, nil
}

// Node implements Noder interface
func (_m *SystemSettings) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "SystemSettings",
		Fields: make([]*Field, 5),
		Edges:  make([]*Edge, 0),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Key); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "key",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Value); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "map[string]interface {}",
		Name:  "value",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Description); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "description",
		Value: string(buf),
	}
	return node, nil
}

// Node implements Noder interface
func (_m *Thread) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "Thread",
		Fields: make([]*Field, 4),
		Edges:  make([]*Edge, 2),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ProjectID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "int",
		Name:  "project_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ThreadID); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "thread_id",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "Project",
		Name: "project",
	}
	err = _m.QueryProject().
		Select(project.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "Trace",
		Name: "traces",
	}
	err = _m.QueryTraces().
		Select(trace.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *Trace) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "Trace",
		Fields: make([]*Field, 6),
		Edges:  make([]*Edge, 3),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ProjectID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "int",
		Name:  "project_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.TraceID); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "string",
		Name:  "trace_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ThreadID); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "int",
		Name:  "thread_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Cost); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "int64",
		Name:  "cost",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "Project",
		Name: "project",
	}
	err = _m.QueryProject().
		Select(project.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "Thread",
		Name: "thread",
	}
	err = _m.QueryThread().
		Select(thread.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[2] = &Edge{
		Type: "Request",
		Name: "requests",
	}
	err = _m.QueryRequests().
		Select(request.FieldID).
		Scan(ctx, &node.Edges[2].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *UsageLog) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "UsageLog",
		Fields: make([]*Field, 24),
		Edges:  make([]*Edge, 4),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.RequestID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "int",
		Name:  "request_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.APIKeyID); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "int",
		Name:  "api_key_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ProjectID); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "int",
		Name:  "project_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ChannelID); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "int",
		Name:  "channel_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ModelID); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "string",
		Name:  "model_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.PromptTokens); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "int64",
		Name:  "prompt_tokens",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.CompletionTokens); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "int64",
		Name:  "completion_tokens",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.TotalTokens); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "int64",
		Name:  "total_tokens",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.PromptAudioTokens); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "int64",
		Name:  "prompt_audio_tokens",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.PromptCachedTokens); err != nil {
		return nil, err
	}
	node.Fields[11] = &Field{
		Type:  "int64",
		Name:  "prompt_cached_tokens",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.PromptWriteCachedTokens); err != nil {
		return nil, err
	}
	node.Fields[12] = &Field{
		Type:  "int64",
		Name:  "prompt_write_cached_tokens",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.PromptWriteCachedTokens5m); err != nil {
		return nil, err
	}
	node.Fields[13] = &Field{
		Type:  "int64",
		Name:  "prompt_write_cached_tokens_5m",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.PromptWriteCachedTokens1h); err != nil {
		return nil, err
	}
	node.Fields[14] = &Field{
		Type:  "int64",
		Name:  "prompt_write_cached_tokens_1h",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.CompletionAudioTokens); err != nil {
		return nil, err
	}
	node.Fields[15] = &Field{
		Type:  "int64",
		Name:  "completion_audio_tokens",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.CompletionReasoningTokens); err != nil {
		return nil, err
	}
	node.Fields[16] = &Field{
		Type:  "int64",
		Name:  "completion_reasoning_tokens",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.CompletionAcceptedPredictionTokens); err != nil {
		return nil, err
	}
	node.Fields[17] = &Field{
		Type:  "int64",
		Name:  "completion_accepted_prediction_tokens",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.CompletionRejectedPredictionTokens); err != nil {
		return nil, err
	}
	node.Fields[18] = &Field{
		Type:  "int64",
		Name:  "completion_rejected_prediction_tokens",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Source); err != nil {
		return nil, err
	}
	node.Fields[19] = &Field{
		Type:  "usagelog.Source",
		Name:  "source",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Format); err != nil {
		return nil, err
	}
	node.Fields[20] = &Field{
		Type:  "string",
		Name:  "format",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.TotalCost); err != nil {
		return nil, err
	}
	node.Fields[21] = &Field{
		Type:  "float64",
		Name:  "total_cost",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.CostItems); err != nil {
		return nil, err
	}
	node.Fields[22] = &Field{
		Type:  "[]objects.CostItem",
		Name:  "cost_items",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.CostPriceReferenceID); err != nil {
		return nil, err
	}
	node.Fields[23] = &Field{
		Type:  "string",
		Name:  "cost_price_reference_id",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "Request",
		Name: "request",
	}
	err = _m.QueryRequest().
		Select(request.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "APIKey",
		Name: "api_key",
	}
	err = _m.QueryAPIKey().
		Select(apikey.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[2] = &Edge{
		Type: "Project",
		Name: "project",
	}
	err = _m.QueryProject().
		Select(project.FieldID).
		Scan(ctx, &node.Edges[2].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[3] = &Edge{
		Type: "Channel",
		Name: "channel",
	}
	err = _m.QueryChannel().
		Select(channel.FieldID).
		Scan(ctx, &node.Edges[3].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *User) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "User",
		Fields: make([]*Field, 13),
		Edges:  make([]*Edge, 9),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Email); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "string",
		Name:  "email",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Status); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "user.Status",
		Name:  "status",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.PreferLanguage); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "string",
		Name:  "prefer_language",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Password); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "string",
		Name:  "password",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.FirstName); err != nil {
		return nil, err
	}
	node.Fields[6] = &Field{
		Type:  "string",
		Name:  "first_name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.LastName); err != nil {
		return nil, err
	}
	node.Fields[7] = &Field{
		Type:  "string",
		Name:  "last_name",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Avatar); err != nil {
		return nil, err
	}
	node.Fields[8] = &Field{
		Type:  "string",
		Name:  "avatar",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.IsOwner); err != nil {
		return nil, err
	}
	node.Fields[9] = &Field{
		Type:  "bool",
		Name:  "is_owner",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Quota); err != nil {
		return nil, err
	}
	node.Fields[10] = &Field{
		Type:  "int64",
		Name:  "quota",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UsedQuota); err != nil {
		return nil, err
	}
	node.Fields[11] = &Field{
		Type:  "int64",
		Name:  "used_quota",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Scopes); err != nil {
		return nil, err
	}
	node.Fields[12] = &Field{
		Type:  "[]string",
		Name:  "scopes",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "Project",
		Name: "projects",
	}
	err = _m.QueryProjects().
		Select(project.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "APIKey",
		Name: "api_keys",
	}
	err = _m.QueryAPIKeys().
		Select(apikey.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[2] = &Edge{
		Type: "Role",
		Name: "roles",
	}
	err = _m.QueryRoles().
		Select(role.FieldID).
		Scan(ctx, &node.Edges[2].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[3] = &Edge{
		Type: "ChannelOverrideTemplate",
		Name: "channel_override_templates",
	}
	err = _m.QueryChannelOverrideTemplates().
		Select(channeloverridetemplate.FieldID).
		Scan(ctx, &node.Edges[3].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[4] = &Edge{
		Type: "ConsumptionRecord",
		Name: "consumption_records",
	}
	err = _m.QueryConsumptionRecords().
		Select(consumptionrecord.FieldID).
		Scan(ctx, &node.Edges[4].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[5] = &Edge{
		Type: "RedemptionCode",
		Name: "redemption_codes",
	}
	err = _m.QueryRedemptionCodes().
		Select(redemptioncode.FieldID).
		Scan(ctx, &node.Edges[5].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[6] = &Edge{
		Type: "RechargeRecord",
		Name: "recharge_records",
	}
	err = _m.QueryRechargeRecords().
		Select(rechargerecord.FieldID).
		Scan(ctx, &node.Edges[6].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[7] = &Edge{
		Type: "UserProject",
		Name: "project_users",
	}
	err = _m.QueryProjectUsers().
		Select(userproject.FieldID).
		Scan(ctx, &node.Edges[7].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[8] = &Edge{
		Type: "UserRole",
		Name: "user_roles",
	}
	err = _m.QueryUserRoles().
		Select(userrole.FieldID).
		Scan(ctx, &node.Edges[8].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *UserProject) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "UserProject",
		Fields: make([]*Field, 6),
		Edges:  make([]*Edge, 2),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UserID); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "int",
		Name:  "user_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.ProjectID); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "int",
		Name:  "project_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.IsOwner); err != nil {
		return nil, err
	}
	node.Fields[4] = &Field{
		Type:  "bool",
		Name:  "is_owner",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.Scopes); err != nil {
		return nil, err
	}
	node.Fields[5] = &Field{
		Type:  "[]string",
		Name:  "scopes",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "User",
		Name: "user",
	}
	err = _m.QueryUser().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "Project",
		Name: "project",
	}
	err = _m.QueryProject().
		Select(project.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node implements Noder interface
func (_m *UserRole) Node(ctx context.Context) (node *Node, err error) {
	node = &Node{
		ID:     _m.ID,
		Type:   "UserRole",
		Fields: make([]*Field, 4),
		Edges:  make([]*Edge, 2),
	}
	var buf []byte
	if buf, err = json.Marshal(_m.UserID); err != nil {
		return nil, err
	}
	node.Fields[0] = &Field{
		Type:  "int",
		Name:  "user_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.RoleID); err != nil {
		return nil, err
	}
	node.Fields[1] = &Field{
		Type:  "int",
		Name:  "role_id",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.CreatedAt); err != nil {
		return nil, err
	}
	node.Fields[2] = &Field{
		Type:  "time.Time",
		Name:  "created_at",
		Value: string(buf),
	}
	if buf, err = json.Marshal(_m.UpdatedAt); err != nil {
		return nil, err
	}
	node.Fields[3] = &Field{
		Type:  "time.Time",
		Name:  "updated_at",
		Value: string(buf),
	}
	node.Edges[0] = &Edge{
		Type: "User",
		Name: "user",
	}
	err = _m.QueryUser().
		Select(user.FieldID).
		Scan(ctx, &node.Edges[0].IDs)
	if err != nil {
		return nil, err
	}
	node.Edges[1] = &Edge{
		Type: "Role",
		Name: "role",
	}
	err = _m.QueryRole().
		Select(role.FieldID).
		Scan(ctx, &node.Edges[1].IDs)
	if err != nil {
		return nil, err
	}
	return node, nil
}

// Node returns the node with given global ID.
//
// This API helpful in case you want to build
// an administrator tool to browser all types in system.
func (c *Client) Node(ctx context.Context, id int) (*Node, error) {
	n, err := c.Noder(ctx, id)
	if err != nil {
		return nil, err
	}
	return n.Node(ctx)
}
