// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/project"
)

// Project is the model entity for the Project schema.
type Project struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// project name
	Name string `json:"name,omitempty"`
	// project description
	Description string `json:"description,omitempty"`
	// project status
	Status project.Status `json:"status,omitempty"`
	// 当前项目额度
	Quota int64 `json:"quota,omitempty"`
	// 已使用额度
	UsedQuota int64 `json:"used_quota,omitempty"`
	// Billing group: default/vip/svip
	Group string `json:"group,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectQuery when eager-loading is set.
	Edges        ProjectEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProjectEdges holds the relations/edges for other nodes in the graph.
type ProjectEdges struct {
	// Users holds the value of the users edge.
	Users []*User `json:"users,omitempty"`
	// Roles holds the value of the roles edge.
	Roles []*Role `json:"roles,omitempty"`
	// APIKeys holds the value of the api_keys edge.
	APIKeys []*APIKey `json:"api_keys,omitempty"`
	// Requests holds the value of the requests edge.
	Requests []*Request `json:"requests,omitempty"`
	// UsageLogs holds the value of the usage_logs edge.
	UsageLogs []*UsageLog `json:"usage_logs,omitempty"`
	// Threads holds the value of the threads edge.
	Threads []*Thread `json:"threads,omitempty"`
	// Traces holds the value of the traces edge.
	Traces []*Trace `json:"traces,omitempty"`
	// ConsumptionRecords holds the value of the consumption_records edge.
	ConsumptionRecords []*ConsumptionRecord `json:"consumption_records,omitempty"`
	// RechargeRecords holds the value of the recharge_records edge.
	RechargeRecords []*RechargeRecord `json:"recharge_records,omitempty"`
	// ProjectUsers holds the value of the project_users edge.
	ProjectUsers []*UserProject `json:"project_users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [10]bool
	// totalCount holds the count of the edges above.
	totalCount [10]map[string]int

	namedUsers              map[string][]*User
	namedRoles              map[string][]*Role
	namedAPIKeys            map[string][]*APIKey
	namedRequests           map[string][]*Request
	namedUsageLogs          map[string][]*UsageLog
	namedThreads            map[string][]*Thread
	namedTraces             map[string][]*Trace
	namedConsumptionRecords map[string][]*ConsumptionRecord
	namedRechargeRecords    map[string][]*RechargeRecord
	namedProjectUsers       map[string][]*UserProject
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// RolesOrErr returns the Roles value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) RolesOrErr() ([]*Role, error) {
	if e.loadedTypes[1] {
		return e.Roles, nil
	}
	return nil, &NotLoadedError{edge: "roles"}
}

// APIKeysOrErr returns the APIKeys value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) APIKeysOrErr() ([]*APIKey, error) {
	if e.loadedTypes[2] {
		return e.APIKeys, nil
	}
	return nil, &NotLoadedError{edge: "api_keys"}
}

// RequestsOrErr returns the Requests value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) RequestsOrErr() ([]*Request, error) {
	if e.loadedTypes[3] {
		return e.Requests, nil
	}
	return nil, &NotLoadedError{edge: "requests"}
}

// UsageLogsOrErr returns the UsageLogs value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) UsageLogsOrErr() ([]*UsageLog, error) {
	if e.loadedTypes[4] {
		return e.UsageLogs, nil
	}
	return nil, &NotLoadedError{edge: "usage_logs"}
}

// ThreadsOrErr returns the Threads value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) ThreadsOrErr() ([]*Thread, error) {
	if e.loadedTypes[5] {
		return e.Threads, nil
	}
	return nil, &NotLoadedError{edge: "threads"}
}

// TracesOrErr returns the Traces value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) TracesOrErr() ([]*Trace, error) {
	if e.loadedTypes[6] {
		return e.Traces, nil
	}
	return nil, &NotLoadedError{edge: "traces"}
}

// ConsumptionRecordsOrErr returns the ConsumptionRecords value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) ConsumptionRecordsOrErr() ([]*ConsumptionRecord, error) {
	if e.loadedTypes[7] {
		return e.ConsumptionRecords, nil
	}
	return nil, &NotLoadedError{edge: "consumption_records"}
}

// RechargeRecordsOrErr returns the RechargeRecords value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) RechargeRecordsOrErr() ([]*RechargeRecord, error) {
	if e.loadedTypes[8] {
		return e.RechargeRecords, nil
	}
	return nil, &NotLoadedError{edge: "recharge_records"}
}

// ProjectUsersOrErr returns the ProjectUsers value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) ProjectUsersOrErr() ([]*UserProject, error) {
	if e.loadedTypes[9] {
		return e.ProjectUsers, nil
	}
	return nil, &NotLoadedError{edge: "project_users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Project) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case project.FieldID, project.FieldDeletedAt, project.FieldQuota, project.FieldUsedQuota:
			values[i] = new(sql.NullInt64)
		case project.FieldName, project.FieldDescription, project.FieldStatus, project.FieldGroup:
			values[i] = new(sql.NullString)
		case project.FieldCreatedAt, project.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Project fields.
func (_m *Project) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case project.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case project.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case project.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case project.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case project.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case project.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case project.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = project.Status(value.String)
			}
		case project.FieldQuota:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quota", values[i])
			} else if value.Valid {
				_m.Quota = value.Int64
			}
		case project.FieldUsedQuota:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field used_quota", values[i])
			} else if value.Valid {
				_m.UsedQuota = value.Int64
			}
		case project.FieldGroup:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group", values[i])
			} else if value.Valid {
				_m.Group = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Project.
// This includes values selected through modifiers, order, etc.
func (_m *Project) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsers queries the "users" edge of the Project entity.
func (_m *Project) QueryUsers() *UserQuery {
	return NewProjectClient(_m.config).QueryUsers(_m)
}

// QueryRoles queries the "roles" edge of the Project entity.
func (_m *Project) QueryRoles() *RoleQuery {
	return NewProjectClient(_m.config).QueryRoles(_m)
}

// QueryAPIKeys queries the "api_keys" edge of the Project entity.
func (_m *Project) QueryAPIKeys() *APIKeyQuery {
	return NewProjectClient(_m.config).QueryAPIKeys(_m)
}

// QueryRequests queries the "requests" edge of the Project entity.
func (_m *Project) QueryRequests() *RequestQuery {
	return NewProjectClient(_m.config).QueryRequests(_m)
}

// QueryUsageLogs queries the "usage_logs" edge of the Project entity.
func (_m *Project) QueryUsageLogs() *UsageLogQuery {
	return NewProjectClient(_m.config).QueryUsageLogs(_m)
}

// QueryThreads queries the "threads" edge of the Project entity.
func (_m *Project) QueryThreads() *ThreadQuery {
	return NewProjectClient(_m.config).QueryThreads(_m)
}

// QueryTraces queries the "traces" edge of the Project entity.
func (_m *Project) QueryTraces() *TraceQuery {
	return NewProjectClient(_m.config).QueryTraces(_m)
}

// QueryConsumptionRecords queries the "consumption_records" edge of the Project entity.
func (_m *Project) QueryConsumptionRecords() *ConsumptionRecordQuery {
	return NewProjectClient(_m.config).QueryConsumptionRecords(_m)
}

// QueryRechargeRecords queries the "recharge_records" edge of the Project entity.
func (_m *Project) QueryRechargeRecords() *RechargeRecordQuery {
	return NewProjectClient(_m.config).QueryRechargeRecords(_m)
}

// QueryProjectUsers queries the "project_users" edge of the Project entity.
func (_m *Project) QueryProjectUsers() *UserProjectQuery {
	return NewProjectClient(_m.config).QueryProjectUsers(_m)
}

// Update returns a builder for updating this Project.
// Note that you need to call Project.Unwrap() before calling this method if this Project
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Project) Update() *ProjectUpdateOne {
	return NewProjectClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Project entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Project) Unwrap() *Project {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Project is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Project) String() string {
	var builder strings.Builder
	builder.WriteString("Project(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("quota=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quota))
	builder.WriteString(", ")
	builder.WriteString("used_quota=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsedQuota))
	builder.WriteString(", ")
	builder.WriteString("group=")
	builder.WriteString(_m.Group)
	builder.WriteByte(')')
	return builder.String()
}

// NamedUsers returns the Users named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Project) NamedUsers(name string) ([]*User, error) {
	if _m.Edges.namedUsers == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedUsers[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Project) appendNamedUsers(name string, edges ...*User) {
	if _m.Edges.namedUsers == nil {
		_m.Edges.namedUsers = make(map[string][]*User)
	}
	if len(edges) == 0 {
		_m.Edges.namedUsers[name] = []*User{}
	} else {
		_m.Edges.namedUsers[name] = append(_m.Edges.namedUsers[name], edges...)
	}
}

// NamedRoles returns the Roles named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Project) NamedRoles(name string) ([]*Role, error) {
	if _m.Edges.namedRoles == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedRoles[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Project) appendNamedRoles(name string, edges ...*Role) {
	if _m.Edges.namedRoles == nil {
		_m.Edges.namedRoles = make(map[string][]*Role)
	}
	if len(edges) == 0 {
		_m.Edges.namedRoles[name] = []*Role{}
	} else {
		_m.Edges.namedRoles[name] = append(_m.Edges.namedRoles[name], edges...)
	}
}

// NamedAPIKeys returns the APIKeys named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Project) NamedAPIKeys(name string) ([]*APIKey, error) {
	if _m.Edges.namedAPIKeys == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedAPIKeys[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Project) appendNamedAPIKeys(name string, edges ...*APIKey) {
	if _m.Edges.namedAPIKeys == nil {
		_m.Edges.namedAPIKeys = make(map[string][]*APIKey)
	}
	if len(edges) == 0 {
		_m.Edges.namedAPIKeys[name] = []*APIKey{}
	} else {
		_m.Edges.namedAPIKeys[name] = append(_m.Edges.namedAPIKeys[name], edges...)
	}
}

// NamedRequests returns the Requests named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Project) NamedRequests(name string) ([]*Request, error) {
	if _m.Edges.namedRequests == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedRequests[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Project) appendNamedRequests(name string, edges ...*Request) {
	if _m.Edges.namedRequests == nil {
		_m.Edges.namedRequests = make(map[string][]*Request)
	}
	if len(edges) == 0 {
		_m.Edges.namedRequests[name] = []*Request{}
	} else {
		_m.Edges.namedRequests[name] = append(_m.Edges.namedRequests[name], edges...)
	}
}

// NamedUsageLogs returns the UsageLogs named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Project) NamedUsageLogs(name string) ([]*UsageLog, error) {
	if _m.Edges.namedUsageLogs == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedUsageLogs[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Project) appendNamedUsageLogs(name string, edges ...*UsageLog) {
	if _m.Edges.namedUsageLogs == nil {
		_m.Edges.namedUsageLogs = make(map[string][]*UsageLog)
	}
	if len(edges) == 0 {
		_m.Edges.namedUsageLogs[name] = []*UsageLog{}
	} else {
		_m.Edges.namedUsageLogs[name] = append(_m.Edges.namedUsageLogs[name], edges...)
	}
}

// NamedThreads returns the Threads named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Project) NamedThreads(name string) ([]*Thread, error) {
	if _m.Edges.namedThreads == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedThreads[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Project) appendNamedThreads(name string, edges ...*Thread) {
	if _m.Edges.namedThreads == nil {
		_m.Edges.namedThreads = make(map[string][]*Thread)
	}
	if len(edges) == 0 {
		_m.Edges.namedThreads[name] = []*Thread{}
	} else {
		_m.Edges.namedThreads[name] = append(_m.Edges.namedThreads[name], edges...)
	}
}

// NamedTraces returns the Traces named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Project) NamedTraces(name string) ([]*Trace, error) {
	if _m.Edges.namedTraces == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedTraces[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Project) appendNamedTraces(name string, edges ...*Trace) {
	if _m.Edges.namedTraces == nil {
		_m.Edges.namedTraces = make(map[string][]*Trace)
	}
	if len(edges) == 0 {
		_m.Edges.namedTraces[name] = []*Trace{}
	} else {
		_m.Edges.namedTraces[name] = append(_m.Edges.namedTraces[name], edges...)
	}
}

// NamedConsumptionRecords returns the ConsumptionRecords named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Project) NamedConsumptionRecords(name string) ([]*ConsumptionRecord, error) {
	if _m.Edges.namedConsumptionRecords == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedConsumptionRecords[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Project) appendNamedConsumptionRecords(name string, edges ...*ConsumptionRecord) {
	if _m.Edges.namedConsumptionRecords == nil {
		_m.Edges.namedConsumptionRecords = make(map[string][]*ConsumptionRecord)
	}
	if len(edges) == 0 {
		_m.Edges.namedConsumptionRecords[name] = []*ConsumptionRecord{}
	} else {
		_m.Edges.namedConsumptionRecords[name] = append(_m.Edges.namedConsumptionRecords[name], edges...)
	}
}

// NamedRechargeRecords returns the RechargeRecords named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Project) NamedRechargeRecords(name string) ([]*RechargeRecord, error) {
	if _m.Edges.namedRechargeRecords == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedRechargeRecords[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Project) appendNamedRechargeRecords(name string, edges ...*RechargeRecord) {
	if _m.Edges.namedRechargeRecords == nil {
		_m.Edges.namedRechargeRecords = make(map[string][]*RechargeRecord)
	}
	if len(edges) == 0 {
		_m.Edges.namedRechargeRecords[name] = []*RechargeRecord{}
	} else {
		_m.Edges.namedRechargeRecords[name] = append(_m.Edges.namedRechargeRecords[name], edges...)
	}
}

// NamedProjectUsers returns the ProjectUsers named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Project) NamedProjectUsers(name string) ([]*UserProject, error) {
	if _m.Edges.namedProjectUsers == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedProjectUsers[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Project) appendNamedProjectUsers(name string, edges ...*UserProject) {
	if _m.Edges.namedProjectUsers == nil {
		_m.Edges.namedProjectUsers = make(map[string][]*UserProject)
	}
	if len(edges) == 0 {
		_m.Edges.namedProjectUsers[name] = []*UserProject{}
	} else {
		_m.Edges.namedProjectUsers[name] = append(_m.Edges.namedProjectUsers[name], edges...)
	}
}

// Projects is a parsable slice of Project.
type Projects []*Project
