// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/ent/rechargerecord"
	"github.com/looplj/axonhub/internal/ent/redemptioncode"
	"github.com/looplj/axonhub/internal/ent/user"
)

// RechargeRecord is the model entity for the RechargeRecord schema.
type RechargeRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// User ID
	UserID int `json:"user_id,omitempty"`
	// Project ID
	ProjectID int `json:"project_id,omitempty"`
	// Redemption code ID
	CodeID int `json:"code_id,omitempty"`
	// Recharge amount
	Amount int64 `json:"amount,omitempty"`
	// Status holds the value of the "status" field.
	Status rechargerecord.Status `json:"status,omitempty"`
	// Trace ID
	TraceID string `json:"trace_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RechargeRecordQuery when eager-loading is set.
	Edges        RechargeRecordEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RechargeRecordEdges holds the relations/edges for other nodes in the graph.
type RechargeRecordEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// RedemptionCode holds the value of the redemption_code edge.
	RedemptionCode *RedemptionCode `json:"redemption_code,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
	// totalCount holds the count of the edges above.
	totalCount [3]map[string]int
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RechargeRecordEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RechargeRecordEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// RedemptionCodeOrErr returns the RedemptionCode value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RechargeRecordEdges) RedemptionCodeOrErr() (*RedemptionCode, error) {
	if e.RedemptionCode != nil {
		return e.RedemptionCode, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: redemptioncode.Label}
	}
	return nil, &NotLoadedError{edge: "redemption_code"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RechargeRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rechargerecord.FieldID, rechargerecord.FieldUserID, rechargerecord.FieldProjectID, rechargerecord.FieldCodeID, rechargerecord.FieldAmount:
			values[i] = new(sql.NullInt64)
		case rechargerecord.FieldStatus, rechargerecord.FieldTraceID:
			values[i] = new(sql.NullString)
		case rechargerecord.FieldCreatedAt, rechargerecord.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RechargeRecord fields.
func (_m *RechargeRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rechargerecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case rechargerecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case rechargerecord.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case rechargerecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case rechargerecord.FieldProjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[i])
			} else if value.Valid {
				_m.ProjectID = int(value.Int64)
			}
		case rechargerecord.FieldCodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field code_id", values[i])
			} else if value.Valid {
				_m.CodeID = int(value.Int64)
			}
		case rechargerecord.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Int64
			}
		case rechargerecord.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = rechargerecord.Status(value.String)
			}
		case rechargerecord.FieldTraceID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trace_id", values[i])
			} else if value.Valid {
				_m.TraceID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RechargeRecord.
// This includes values selected through modifiers, order, etc.
func (_m *RechargeRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the RechargeRecord entity.
func (_m *RechargeRecord) QueryUser() *UserQuery {
	return NewRechargeRecordClient(_m.config).QueryUser(_m)
}

// QueryProject queries the "project" edge of the RechargeRecord entity.
func (_m *RechargeRecord) QueryProject() *ProjectQuery {
	return NewRechargeRecordClient(_m.config).QueryProject(_m)
}

// QueryRedemptionCode queries the "redemption_code" edge of the RechargeRecord entity.
func (_m *RechargeRecord) QueryRedemptionCode() *RedemptionCodeQuery {
	return NewRechargeRecordClient(_m.config).QueryRedemptionCode(_m)
}

// Update returns a builder for updating this RechargeRecord.
// Note that you need to call RechargeRecord.Unwrap() before calling this method if this RechargeRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RechargeRecord) Update() *RechargeRecordUpdateOne {
	return NewRechargeRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RechargeRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RechargeRecord) Unwrap() *RechargeRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RechargeRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RechargeRecord) String() string {
	var builder strings.Builder
	builder.WriteString("RechargeRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("project_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProjectID))
	builder.WriteString(", ")
	builder.WriteString("code_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CodeID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("trace_id=")
	builder.WriteString(_m.TraceID)
	builder.WriteByte(')')
	return builder.String()
}

// RechargeRecords is a parsable slice of RechargeRecord.
type RechargeRecords []*RechargeRecord
