// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/ent/rechargerecord"
	"github.com/looplj/axonhub/internal/ent/redemptioncode"
	"github.com/looplj/axonhub/internal/ent/user"
)

// RechargeRecordCreate is the builder for creating a RechargeRecord entity.
type RechargeRecordCreate struct {
	config
	mutation *RechargeRecordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *RechargeRecordCreate) SetCreatedAt(v time.Time) *RechargeRecordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RechargeRecordCreate) SetNillableCreatedAt(v *time.Time) *RechargeRecordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RechargeRecordCreate) SetUpdatedAt(v time.Time) *RechargeRecordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RechargeRecordCreate) SetNillableUpdatedAt(v *time.Time) *RechargeRecordCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RechargeRecordCreate) SetUserID(v int) *RechargeRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProjectID sets the "project_id" field.
func (_c *RechargeRecordCreate) SetProjectID(v int) *RechargeRecordCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetCodeID sets the "code_id" field.
func (_c *RechargeRecordCreate) SetCodeID(v int) *RechargeRecordCreate {
	_c.mutation.SetCodeID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *RechargeRecordCreate) SetAmount(v int64) *RechargeRecordCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *RechargeRecordCreate) SetStatus(v rechargerecord.Status) *RechargeRecordCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RechargeRecordCreate) SetNillableStatus(v *rechargerecord.Status) *RechargeRecordCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetTraceID sets the "trace_id" field.
func (_c *RechargeRecordCreate) SetTraceID(v string) *RechargeRecordCreate {
	_c.mutation.SetTraceID(v)
	return _c
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (_c *RechargeRecordCreate) SetNillableTraceID(v *string) *RechargeRecordCreate {
	if v != nil {
		_c.SetTraceID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *RechargeRecordCreate) SetUser(v *User) *RechargeRecordCreate {
	return _c.SetUserID(v.ID)
}

// SetProject sets the "project" edge to the Project entity.
func (_c *RechargeRecordCreate) SetProject(v *Project) *RechargeRecordCreate {
	return _c.SetProjectID(v.ID)
}

// SetRedemptionCodeID sets the "redemption_code" edge to the RedemptionCode entity by ID.
func (_c *RechargeRecordCreate) SetRedemptionCodeID(id int) *RechargeRecordCreate {
	_c.mutation.SetRedemptionCodeID(id)
	return _c
}

// SetRedemptionCode sets the "redemption_code" edge to the RedemptionCode entity.
func (_c *RechargeRecordCreate) SetRedemptionCode(v *RedemptionCode) *RechargeRecordCreate {
	return _c.SetRedemptionCodeID(v.ID)
}

// Mutation returns the RechargeRecordMutation object of the builder.
func (_c *RechargeRecordCreate) Mutation() *RechargeRecordMutation {
	return _c.mutation
}

// Save creates the RechargeRecord in the database.
func (_c *RechargeRecordCreate) Save(ctx context.Context) (*RechargeRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RechargeRecordCreate) SaveX(ctx context.Context) *RechargeRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RechargeRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RechargeRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RechargeRecordCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rechargerecord.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := rechargerecord.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := rechargerecord.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RechargeRecordCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RechargeRecord.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RechargeRecord.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RechargeRecord.user_id"`)}
	}
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "RechargeRecord.project_id"`)}
	}
	if _, ok := _c.mutation.CodeID(); !ok {
		return &ValidationError{Name: "code_id", err: errors.New(`ent: missing required field "RechargeRecord.code_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "RechargeRecord.amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RechargeRecord.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := rechargerecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RechargeRecord.status": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "RechargeRecord.user"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "RechargeRecord.project"`)}
	}
	if len(_c.mutation.RedemptionCodeIDs()) == 0 {
		return &ValidationError{Name: "redemption_code", err: errors.New(`ent: missing required edge "RechargeRecord.redemption_code"`)}
	}
	return nil
}

func (_c *RechargeRecordCreate) sqlSave(ctx context.Context) (*RechargeRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RechargeRecordCreate) createSpec() (*RechargeRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &RechargeRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rechargerecord.Table, sqlgraph.NewFieldSpec(rechargerecord.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rechargerecord.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargerecord.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(rechargerecord.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(rechargerecord.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.TraceID(); ok {
		_spec.SetField(rechargerecord.FieldTraceID, field.TypeString, value)
		_node.TraceID = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargerecord.UserTable,
			Columns: []string{rechargerecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargerecord.ProjectTable,
			Columns: []string{rechargerecord.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RedemptionCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rechargerecord.RedemptionCodeTable,
			Columns: []string{rechargerecord.RedemptionCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redemptioncode.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CodeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RechargeRecord.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RechargeRecordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RechargeRecordCreate) OnConflict(opts ...sql.ConflictOption) *RechargeRecordUpsertOne {
	_c.conflict = opts
	return &RechargeRecordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RechargeRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RechargeRecordCreate) OnConflictColumns(columns ...string) *RechargeRecordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RechargeRecordUpsertOne{
		create: _c,
	}
}

type (
	// RechargeRecordUpsertOne is the builder for "upsert"-ing
	//  one RechargeRecord node.
	RechargeRecordUpsertOne struct {
		create *RechargeRecordCreate
	}

	// RechargeRecordUpsert is the "OnConflict" setter.
	RechargeRecordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeRecordUpsert) SetUpdatedAt(v time.Time) *RechargeRecordUpsert {
	u.Set(rechargerecord.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeRecordUpsert) UpdateUpdatedAt() *RechargeRecordUpsert {
	u.SetExcluded(rechargerecord.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *RechargeRecordUpsert) SetUserID(v int) *RechargeRecordUpsert {
	u.Set(rechargerecord.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RechargeRecordUpsert) UpdateUserID() *RechargeRecordUpsert {
	u.SetExcluded(rechargerecord.FieldUserID)
	return u
}

// SetProjectID sets the "project_id" field.
func (u *RechargeRecordUpsert) SetProjectID(v int) *RechargeRecordUpsert {
	u.Set(rechargerecord.FieldProjectID, v)
	return u
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *RechargeRecordUpsert) UpdateProjectID() *RechargeRecordUpsert {
	u.SetExcluded(rechargerecord.FieldProjectID)
	return u
}

// SetCodeID sets the "code_id" field.
func (u *RechargeRecordUpsert) SetCodeID(v int) *RechargeRecordUpsert {
	u.Set(rechargerecord.FieldCodeID, v)
	return u
}

// UpdateCodeID sets the "code_id" field to the value that was provided on create.
func (u *RechargeRecordUpsert) UpdateCodeID() *RechargeRecordUpsert {
	u.SetExcluded(rechargerecord.FieldCodeID)
	return u
}

// SetAmount sets the "amount" field.
func (u *RechargeRecordUpsert) SetAmount(v int64) *RechargeRecordUpsert {
	u.Set(rechargerecord.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RechargeRecordUpsert) UpdateAmount() *RechargeRecordUpsert {
	u.SetExcluded(rechargerecord.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *RechargeRecordUpsert) AddAmount(v int64) *RechargeRecordUpsert {
	u.Add(rechargerecord.FieldAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *RechargeRecordUpsert) SetStatus(v rechargerecord.Status) *RechargeRecordUpsert {
	u.Set(rechargerecord.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RechargeRecordUpsert) UpdateStatus() *RechargeRecordUpsert {
	u.SetExcluded(rechargerecord.FieldStatus)
	return u
}

// SetTraceID sets the "trace_id" field.
func (u *RechargeRecordUpsert) SetTraceID(v string) *RechargeRecordUpsert {
	u.Set(rechargerecord.FieldTraceID, v)
	return u
}

// UpdateTraceID sets the "trace_id" field to the value that was provided on create.
func (u *RechargeRecordUpsert) UpdateTraceID() *RechargeRecordUpsert {
	u.SetExcluded(rechargerecord.FieldTraceID)
	return u
}

// ClearTraceID clears the value of the "trace_id" field.
func (u *RechargeRecordUpsert) ClearTraceID() *RechargeRecordUpsert {
	u.SetNull(rechargerecord.FieldTraceID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RechargeRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RechargeRecordUpsertOne) UpdateNewValues() *RechargeRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(rechargerecord.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RechargeRecord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RechargeRecordUpsertOne) Ignore() *RechargeRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RechargeRecordUpsertOne) DoNothing() *RechargeRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RechargeRecordCreate.OnConflict
// documentation for more info.
func (u *RechargeRecordUpsertOne) Update(set func(*RechargeRecordUpsert)) *RechargeRecordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RechargeRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeRecordUpsertOne) SetUpdatedAt(v time.Time) *RechargeRecordUpsertOne {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeRecordUpsertOne) UpdateUpdatedAt() *RechargeRecordUpsertOne {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *RechargeRecordUpsertOne) SetUserID(v int) *RechargeRecordUpsertOne {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RechargeRecordUpsertOne) UpdateUserID() *RechargeRecordUpsertOne {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetProjectID sets the "project_id" field.
func (u *RechargeRecordUpsertOne) SetProjectID(v int) *RechargeRecordUpsertOne {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *RechargeRecordUpsertOne) UpdateProjectID() *RechargeRecordUpsertOne {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.UpdateProjectID()
	})
}

// SetCodeID sets the "code_id" field.
func (u *RechargeRecordUpsertOne) SetCodeID(v int) *RechargeRecordUpsertOne {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.SetCodeID(v)
	})
}

// UpdateCodeID sets the "code_id" field to the value that was provided on create.
func (u *RechargeRecordUpsertOne) UpdateCodeID() *RechargeRecordUpsertOne {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.UpdateCodeID()
	})
}

// SetAmount sets the "amount" field.
func (u *RechargeRecordUpsertOne) SetAmount(v int64) *RechargeRecordUpsertOne {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *RechargeRecordUpsertOne) AddAmount(v int64) *RechargeRecordUpsertOne {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RechargeRecordUpsertOne) UpdateAmount() *RechargeRecordUpsertOne {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *RechargeRecordUpsertOne) SetStatus(v rechargerecord.Status) *RechargeRecordUpsertOne {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RechargeRecordUpsertOne) UpdateStatus() *RechargeRecordUpsertOne {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.UpdateStatus()
	})
}

// SetTraceID sets the "trace_id" field.
func (u *RechargeRecordUpsertOne) SetTraceID(v string) *RechargeRecordUpsertOne {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.SetTraceID(v)
	})
}

// UpdateTraceID sets the "trace_id" field to the value that was provided on create.
func (u *RechargeRecordUpsertOne) UpdateTraceID() *RechargeRecordUpsertOne {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.UpdateTraceID()
	})
}

// ClearTraceID clears the value of the "trace_id" field.
func (u *RechargeRecordUpsertOne) ClearTraceID() *RechargeRecordUpsertOne {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.ClearTraceID()
	})
}

// Exec executes the query.
func (u *RechargeRecordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RechargeRecordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RechargeRecordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RechargeRecordUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RechargeRecordUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RechargeRecordCreateBulk is the builder for creating many RechargeRecord entities in bulk.
type RechargeRecordCreateBulk struct {
	config
	err      error
	builders []*RechargeRecordCreate
	conflict []sql.ConflictOption
}

// Save creates the RechargeRecord entities in the database.
func (_c *RechargeRecordCreateBulk) Save(ctx context.Context) ([]*RechargeRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RechargeRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RechargeRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RechargeRecordCreateBulk) SaveX(ctx context.Context) []*RechargeRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RechargeRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RechargeRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RechargeRecord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RechargeRecordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RechargeRecordCreateBulk) OnConflict(opts ...sql.ConflictOption) *RechargeRecordUpsertBulk {
	_c.conflict = opts
	return &RechargeRecordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RechargeRecord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RechargeRecordCreateBulk) OnConflictColumns(columns ...string) *RechargeRecordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RechargeRecordUpsertBulk{
		create: _c,
	}
}

// RechargeRecordUpsertBulk is the builder for "upsert"-ing
// a bulk of RechargeRecord nodes.
type RechargeRecordUpsertBulk struct {
	create *RechargeRecordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RechargeRecord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RechargeRecordUpsertBulk) UpdateNewValues() *RechargeRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(rechargerecord.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RechargeRecord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RechargeRecordUpsertBulk) Ignore() *RechargeRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RechargeRecordUpsertBulk) DoNothing() *RechargeRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RechargeRecordCreateBulk.OnConflict
// documentation for more info.
func (u *RechargeRecordUpsertBulk) Update(set func(*RechargeRecordUpsert)) *RechargeRecordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RechargeRecordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeRecordUpsertBulk) SetUpdatedAt(v time.Time) *RechargeRecordUpsertBulk {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeRecordUpsertBulk) UpdateUpdatedAt() *RechargeRecordUpsertBulk {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *RechargeRecordUpsertBulk) SetUserID(v int) *RechargeRecordUpsertBulk {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RechargeRecordUpsertBulk) UpdateUserID() *RechargeRecordUpsertBulk {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.UpdateUserID()
	})
}

// SetProjectID sets the "project_id" field.
func (u *RechargeRecordUpsertBulk) SetProjectID(v int) *RechargeRecordUpsertBulk {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *RechargeRecordUpsertBulk) UpdateProjectID() *RechargeRecordUpsertBulk {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.UpdateProjectID()
	})
}

// SetCodeID sets the "code_id" field.
func (u *RechargeRecordUpsertBulk) SetCodeID(v int) *RechargeRecordUpsertBulk {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.SetCodeID(v)
	})
}

// UpdateCodeID sets the "code_id" field to the value that was provided on create.
func (u *RechargeRecordUpsertBulk) UpdateCodeID() *RechargeRecordUpsertBulk {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.UpdateCodeID()
	})
}

// SetAmount sets the "amount" field.
func (u *RechargeRecordUpsertBulk) SetAmount(v int64) *RechargeRecordUpsertBulk {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *RechargeRecordUpsertBulk) AddAmount(v int64) *RechargeRecordUpsertBulk {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RechargeRecordUpsertBulk) UpdateAmount() *RechargeRecordUpsertBulk {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *RechargeRecordUpsertBulk) SetStatus(v rechargerecord.Status) *RechargeRecordUpsertBulk {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RechargeRecordUpsertBulk) UpdateStatus() *RechargeRecordUpsertBulk {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.UpdateStatus()
	})
}

// SetTraceID sets the "trace_id" field.
func (u *RechargeRecordUpsertBulk) SetTraceID(v string) *RechargeRecordUpsertBulk {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.SetTraceID(v)
	})
}

// UpdateTraceID sets the "trace_id" field to the value that was provided on create.
func (u *RechargeRecordUpsertBulk) UpdateTraceID() *RechargeRecordUpsertBulk {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.UpdateTraceID()
	})
}

// ClearTraceID clears the value of the "trace_id" field.
func (u *RechargeRecordUpsertBulk) ClearTraceID() *RechargeRecordUpsertBulk {
	return u.Update(func(s *RechargeRecordUpsert) {
		s.ClearTraceID()
	})
}

// Exec executes the query.
func (u *RechargeRecordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RechargeRecordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RechargeRecordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RechargeRecordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
