// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/sensitiveword"
)

// SensitiveWordCreate is the builder for creating a SensitiveWord entity.
type SensitiveWordCreate struct {
	config
	mutation *SensitiveWordMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SensitiveWordCreate) SetCreatedAt(v time.Time) *SensitiveWordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SensitiveWordCreate) SetNillableCreatedAt(v *time.Time) *SensitiveWordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SensitiveWordCreate) SetUpdatedAt(v time.Time) *SensitiveWordCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SensitiveWordCreate) SetNillableUpdatedAt(v *time.Time) *SensitiveWordCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SensitiveWordCreate) SetDeletedAt(v int) *SensitiveWordCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SensitiveWordCreate) SetNillableDeletedAt(v *int) *SensitiveWordCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetWord sets the "word" field.
func (_c *SensitiveWordCreate) SetWord(v string) *SensitiveWordCreate {
	_c.mutation.SetWord(v)
	return _c
}

// SetType sets the "type" field.
func (_c *SensitiveWordCreate) SetType(v sensitiveword.Type) *SensitiveWordCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *SensitiveWordCreate) SetNillableType(v *sensitiveword.Type) *SensitiveWordCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// Mutation returns the SensitiveWordMutation object of the builder.
func (_c *SensitiveWordCreate) Mutation() *SensitiveWordMutation {
	return _c.mutation
}

// Save creates the SensitiveWord in the database.
func (_c *SensitiveWordCreate) Save(ctx context.Context) (*SensitiveWord, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SensitiveWordCreate) SaveX(ctx context.Context) *SensitiveWord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SensitiveWordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SensitiveWordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SensitiveWordCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if sensitiveword.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized sensitiveword.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := sensitiveword.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if sensitiveword.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sensitiveword.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sensitiveword.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := sensitiveword.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := sensitiveword.DefaultType
		_c.mutation.SetType(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SensitiveWordCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SensitiveWord.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SensitiveWord.updated_at"`)}
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "SensitiveWord.deleted_at"`)}
	}
	if _, ok := _c.mutation.Word(); !ok {
		return &ValidationError{Name: "word", err: errors.New(`ent: missing required field "SensitiveWord.word"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "SensitiveWord.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := sensitiveword.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SensitiveWord.type": %w`, err)}
		}
	}
	return nil
}

func (_c *SensitiveWordCreate) sqlSave(ctx context.Context) (*SensitiveWord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SensitiveWordCreate) createSpec() (*SensitiveWord, *sqlgraph.CreateSpec) {
	var (
		_node = &SensitiveWord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sensitiveword.Table, sqlgraph.NewFieldSpec(sensitiveword.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sensitiveword.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sensitiveword.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(sensitiveword.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Word(); ok {
		_spec.SetField(sensitiveword.FieldWord, field.TypeString, value)
		_node.Word = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(sensitiveword.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SensitiveWord.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SensitiveWordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SensitiveWordCreate) OnConflict(opts ...sql.ConflictOption) *SensitiveWordUpsertOne {
	_c.conflict = opts
	return &SensitiveWordUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SensitiveWord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SensitiveWordCreate) OnConflictColumns(columns ...string) *SensitiveWordUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SensitiveWordUpsertOne{
		create: _c,
	}
}

type (
	// SensitiveWordUpsertOne is the builder for "upsert"-ing
	//  one SensitiveWord node.
	SensitiveWordUpsertOne struct {
		create *SensitiveWordCreate
	}

	// SensitiveWordUpsert is the "OnConflict" setter.
	SensitiveWordUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SensitiveWordUpsert) SetUpdatedAt(v time.Time) *SensitiveWordUpsert {
	u.Set(sensitiveword.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SensitiveWordUpsert) UpdateUpdatedAt() *SensitiveWordUpsert {
	u.SetExcluded(sensitiveword.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SensitiveWordUpsert) SetDeletedAt(v int) *SensitiveWordUpsert {
	u.Set(sensitiveword.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SensitiveWordUpsert) UpdateDeletedAt() *SensitiveWordUpsert {
	u.SetExcluded(sensitiveword.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *SensitiveWordUpsert) AddDeletedAt(v int) *SensitiveWordUpsert {
	u.Add(sensitiveword.FieldDeletedAt, v)
	return u
}

// SetWord sets the "word" field.
func (u *SensitiveWordUpsert) SetWord(v string) *SensitiveWordUpsert {
	u.Set(sensitiveword.FieldWord, v)
	return u
}

// UpdateWord sets the "word" field to the value that was provided on create.
func (u *SensitiveWordUpsert) UpdateWord() *SensitiveWordUpsert {
	u.SetExcluded(sensitiveword.FieldWord)
	return u
}

// SetType sets the "type" field.
func (u *SensitiveWordUpsert) SetType(v sensitiveword.Type) *SensitiveWordUpsert {
	u.Set(sensitiveword.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *SensitiveWordUpsert) UpdateType() *SensitiveWordUpsert {
	u.SetExcluded(sensitiveword.FieldType)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SensitiveWord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SensitiveWordUpsertOne) UpdateNewValues() *SensitiveWordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(sensitiveword.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SensitiveWord.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SensitiveWordUpsertOne) Ignore() *SensitiveWordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SensitiveWordUpsertOne) DoNothing() *SensitiveWordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SensitiveWordCreate.OnConflict
// documentation for more info.
func (u *SensitiveWordUpsertOne) Update(set func(*SensitiveWordUpsert)) *SensitiveWordUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SensitiveWordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SensitiveWordUpsertOne) SetUpdatedAt(v time.Time) *SensitiveWordUpsertOne {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SensitiveWordUpsertOne) UpdateUpdatedAt() *SensitiveWordUpsertOne {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SensitiveWordUpsertOne) SetDeletedAt(v int) *SensitiveWordUpsertOne {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *SensitiveWordUpsertOne) AddDeletedAt(v int) *SensitiveWordUpsertOne {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SensitiveWordUpsertOne) UpdateDeletedAt() *SensitiveWordUpsertOne {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetWord sets the "word" field.
func (u *SensitiveWordUpsertOne) SetWord(v string) *SensitiveWordUpsertOne {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.SetWord(v)
	})
}

// UpdateWord sets the "word" field to the value that was provided on create.
func (u *SensitiveWordUpsertOne) UpdateWord() *SensitiveWordUpsertOne {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.UpdateWord()
	})
}

// SetType sets the "type" field.
func (u *SensitiveWordUpsertOne) SetType(v sensitiveword.Type) *SensitiveWordUpsertOne {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *SensitiveWordUpsertOne) UpdateType() *SensitiveWordUpsertOne {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.UpdateType()
	})
}

// Exec executes the query.
func (u *SensitiveWordUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SensitiveWordCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SensitiveWordUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SensitiveWordUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SensitiveWordUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SensitiveWordCreateBulk is the builder for creating many SensitiveWord entities in bulk.
type SensitiveWordCreateBulk struct {
	config
	err      error
	builders []*SensitiveWordCreate
	conflict []sql.ConflictOption
}

// Save creates the SensitiveWord entities in the database.
func (_c *SensitiveWordCreateBulk) Save(ctx context.Context) ([]*SensitiveWord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SensitiveWord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SensitiveWordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SensitiveWordCreateBulk) SaveX(ctx context.Context) []*SensitiveWord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SensitiveWordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SensitiveWordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SensitiveWord.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SensitiveWordUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SensitiveWordCreateBulk) OnConflict(opts ...sql.ConflictOption) *SensitiveWordUpsertBulk {
	_c.conflict = opts
	return &SensitiveWordUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SensitiveWord.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SensitiveWordCreateBulk) OnConflictColumns(columns ...string) *SensitiveWordUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SensitiveWordUpsertBulk{
		create: _c,
	}
}

// SensitiveWordUpsertBulk is the builder for "upsert"-ing
// a bulk of SensitiveWord nodes.
type SensitiveWordUpsertBulk struct {
	create *SensitiveWordCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SensitiveWord.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SensitiveWordUpsertBulk) UpdateNewValues() *SensitiveWordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(sensitiveword.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SensitiveWord.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SensitiveWordUpsertBulk) Ignore() *SensitiveWordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SensitiveWordUpsertBulk) DoNothing() *SensitiveWordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SensitiveWordCreateBulk.OnConflict
// documentation for more info.
func (u *SensitiveWordUpsertBulk) Update(set func(*SensitiveWordUpsert)) *SensitiveWordUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SensitiveWordUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SensitiveWordUpsertBulk) SetUpdatedAt(v time.Time) *SensitiveWordUpsertBulk {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SensitiveWordUpsertBulk) UpdateUpdatedAt() *SensitiveWordUpsertBulk {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SensitiveWordUpsertBulk) SetDeletedAt(v int) *SensitiveWordUpsertBulk {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *SensitiveWordUpsertBulk) AddDeletedAt(v int) *SensitiveWordUpsertBulk {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SensitiveWordUpsertBulk) UpdateDeletedAt() *SensitiveWordUpsertBulk {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetWord sets the "word" field.
func (u *SensitiveWordUpsertBulk) SetWord(v string) *SensitiveWordUpsertBulk {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.SetWord(v)
	})
}

// UpdateWord sets the "word" field to the value that was provided on create.
func (u *SensitiveWordUpsertBulk) UpdateWord() *SensitiveWordUpsertBulk {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.UpdateWord()
	})
}

// SetType sets the "type" field.
func (u *SensitiveWordUpsertBulk) SetType(v sensitiveword.Type) *SensitiveWordUpsertBulk {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *SensitiveWordUpsertBulk) UpdateType() *SensitiveWordUpsertBulk {
	return u.Update(func(s *SensitiveWordUpsert) {
		s.UpdateType()
	})
}

// Exec executes the query.
func (u *SensitiveWordUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SensitiveWordCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SensitiveWordCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SensitiveWordUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
