// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/systemsettings"
)

// SystemSettingsUpdate is the builder for updating SystemSettings entities.
type SystemSettingsUpdate struct {
	config
	hooks     []Hook
	mutation  *SystemSettingsMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SystemSettingsUpdate builder.
func (_u *SystemSettingsUpdate) Where(ps ...predicate.SystemSettings) *SystemSettingsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemSettingsUpdate) SetUpdatedAt(v time.Time) *SystemSettingsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SystemSettingsUpdate) SetDeletedAt(v int) *SystemSettingsUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SystemSettingsUpdate) SetNillableDeletedAt(v *int) *SystemSettingsUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *SystemSettingsUpdate) AddDeletedAt(v int) *SystemSettingsUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetKey sets the "key" field.
func (_u *SystemSettingsUpdate) SetKey(v string) *SystemSettingsUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *SystemSettingsUpdate) SetNillableKey(v *string) *SystemSettingsUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *SystemSettingsUpdate) SetValue(v map[string]interface{}) *SystemSettingsUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *SystemSettingsUpdate) SetDescription(v string) *SystemSettingsUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SystemSettingsUpdate) SetNillableDescription(v *string) *SystemSettingsUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SystemSettingsUpdate) ClearDescription() *SystemSettingsUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the SystemSettingsMutation object of the builder.
func (_u *SystemSettingsUpdate) Mutation() *SystemSettingsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SystemSettingsUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemSettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SystemSettingsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemSettingsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemSettingsUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if systemsettings.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized systemsettings.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := systemsettings.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SystemSettingsUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SystemSettingsUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SystemSettingsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(systemsettings.Table, systemsettings.Columns, sqlgraph.NewFieldSpec(systemsettings.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemsettings.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(systemsettings.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(systemsettings.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(systemsettings.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(systemsettings.FieldValue, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(systemsettings.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(systemsettings.FieldDescription, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SystemSettingsUpdateOne is the builder for updating a single SystemSettings entity.
type SystemSettingsUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SystemSettingsMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemSettingsUpdateOne) SetUpdatedAt(v time.Time) *SystemSettingsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SystemSettingsUpdateOne) SetDeletedAt(v int) *SystemSettingsUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SystemSettingsUpdateOne) SetNillableDeletedAt(v *int) *SystemSettingsUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *SystemSettingsUpdateOne) AddDeletedAt(v int) *SystemSettingsUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetKey sets the "key" field.
func (_u *SystemSettingsUpdateOne) SetKey(v string) *SystemSettingsUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *SystemSettingsUpdateOne) SetNillableKey(v *string) *SystemSettingsUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *SystemSettingsUpdateOne) SetValue(v map[string]interface{}) *SystemSettingsUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *SystemSettingsUpdateOne) SetDescription(v string) *SystemSettingsUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SystemSettingsUpdateOne) SetNillableDescription(v *string) *SystemSettingsUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SystemSettingsUpdateOne) ClearDescription() *SystemSettingsUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the SystemSettingsMutation object of the builder.
func (_u *SystemSettingsUpdateOne) Mutation() *SystemSettingsMutation {
	return _u.mutation
}

// Where appends a list predicates to the SystemSettingsUpdate builder.
func (_u *SystemSettingsUpdateOne) Where(ps ...predicate.SystemSettings) *SystemSettingsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SystemSettingsUpdateOne) Select(field string, fields ...string) *SystemSettingsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SystemSettings entity.
func (_u *SystemSettingsUpdateOne) Save(ctx context.Context) (*SystemSettings, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemSettingsUpdateOne) SaveX(ctx context.Context) *SystemSettings {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SystemSettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemSettingsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemSettingsUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if systemsettings.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized systemsettings.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := systemsettings.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SystemSettingsUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SystemSettingsUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SystemSettingsUpdateOne) sqlSave(ctx context.Context) (_node *SystemSettings, err error) {
	_spec := sqlgraph.NewUpdateSpec(systemsettings.Table, systemsettings.Columns, sqlgraph.NewFieldSpec(systemsettings.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SystemSettings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemsettings.FieldID)
		for _, f := range fields {
			if !systemsettings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != systemsettings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemsettings.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(systemsettings.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(systemsettings.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(systemsettings.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(systemsettings.FieldValue, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(systemsettings.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(systemsettings.FieldDescription, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SystemSettings{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
