// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/systemsettings"
)

// SystemSettingsCreate is the builder for creating a SystemSettings entity.
type SystemSettingsCreate struct {
	config
	mutation *SystemSettingsMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SystemSettingsCreate) SetCreatedAt(v time.Time) *SystemSettingsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SystemSettingsCreate) SetNillableCreatedAt(v *time.Time) *SystemSettingsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SystemSettingsCreate) SetUpdatedAt(v time.Time) *SystemSettingsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SystemSettingsCreate) SetNillableUpdatedAt(v *time.Time) *SystemSettingsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SystemSettingsCreate) SetDeletedAt(v int) *SystemSettingsCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SystemSettingsCreate) SetNillableDeletedAt(v *int) *SystemSettingsCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetKey sets the "key" field.
func (_c *SystemSettingsCreate) SetKey(v string) *SystemSettingsCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *SystemSettingsCreate) SetValue(v map[string]interface{}) *SystemSettingsCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SystemSettingsCreate) SetDescription(v string) *SystemSettingsCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SystemSettingsCreate) SetNillableDescription(v *string) *SystemSettingsCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// Mutation returns the SystemSettingsMutation object of the builder.
func (_c *SystemSettingsCreate) Mutation() *SystemSettingsMutation {
	return _c.mutation
}

// Save creates the SystemSettings in the database.
func (_c *SystemSettingsCreate) Save(ctx context.Context) (*SystemSettings, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SystemSettingsCreate) SaveX(ctx context.Context) *SystemSettings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemSettingsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemSettingsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SystemSettingsCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if systemsettings.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized systemsettings.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := systemsettings.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if systemsettings.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized systemsettings.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := systemsettings.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := systemsettings.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SystemSettingsCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SystemSettings.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SystemSettings.updated_at"`)}
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "SystemSettings.deleted_at"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "SystemSettings.key"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "SystemSettings.value"`)}
	}
	return nil
}

func (_c *SystemSettingsCreate) sqlSave(ctx context.Context) (*SystemSettings, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SystemSettingsCreate) createSpec() (*SystemSettings, *sqlgraph.CreateSpec) {
	var (
		_node = &SystemSettings{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(systemsettings.Table, sqlgraph.NewFieldSpec(systemsettings.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(systemsettings.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(systemsettings.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(systemsettings.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(systemsettings.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(systemsettings.FieldValue, field.TypeJSON, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(systemsettings.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SystemSettings.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SystemSettingsUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SystemSettingsCreate) OnConflict(opts ...sql.ConflictOption) *SystemSettingsUpsertOne {
	_c.conflict = opts
	return &SystemSettingsUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SystemSettings.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SystemSettingsCreate) OnConflictColumns(columns ...string) *SystemSettingsUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SystemSettingsUpsertOne{
		create: _c,
	}
}

type (
	// SystemSettingsUpsertOne is the builder for "upsert"-ing
	//  one SystemSettings node.
	SystemSettingsUpsertOne struct {
		create *SystemSettingsCreate
	}

	// SystemSettingsUpsert is the "OnConflict" setter.
	SystemSettingsUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SystemSettingsUpsert) SetUpdatedAt(v time.Time) *SystemSettingsUpsert {
	u.Set(systemsettings.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SystemSettingsUpsert) UpdateUpdatedAt() *SystemSettingsUpsert {
	u.SetExcluded(systemsettings.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SystemSettingsUpsert) SetDeletedAt(v int) *SystemSettingsUpsert {
	u.Set(systemsettings.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SystemSettingsUpsert) UpdateDeletedAt() *SystemSettingsUpsert {
	u.SetExcluded(systemsettings.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *SystemSettingsUpsert) AddDeletedAt(v int) *SystemSettingsUpsert {
	u.Add(systemsettings.FieldDeletedAt, v)
	return u
}

// SetKey sets the "key" field.
func (u *SystemSettingsUpsert) SetKey(v string) *SystemSettingsUpsert {
	u.Set(systemsettings.FieldKey, v)
	return u
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *SystemSettingsUpsert) UpdateKey() *SystemSettingsUpsert {
	u.SetExcluded(systemsettings.FieldKey)
	return u
}

// SetValue sets the "value" field.
func (u *SystemSettingsUpsert) SetValue(v map[string]interface{}) *SystemSettingsUpsert {
	u.Set(systemsettings.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SystemSettingsUpsert) UpdateValue() *SystemSettingsUpsert {
	u.SetExcluded(systemsettings.FieldValue)
	return u
}

// SetDescription sets the "description" field.
func (u *SystemSettingsUpsert) SetDescription(v string) *SystemSettingsUpsert {
	u.Set(systemsettings.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SystemSettingsUpsert) UpdateDescription() *SystemSettingsUpsert {
	u.SetExcluded(systemsettings.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *SystemSettingsUpsert) ClearDescription() *SystemSettingsUpsert {
	u.SetNull(systemsettings.FieldDescription)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SystemSettings.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SystemSettingsUpsertOne) UpdateNewValues() *SystemSettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(systemsettings.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SystemSettings.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SystemSettingsUpsertOne) Ignore() *SystemSettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SystemSettingsUpsertOne) DoNothing() *SystemSettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SystemSettingsCreate.OnConflict
// documentation for more info.
func (u *SystemSettingsUpsertOne) Update(set func(*SystemSettingsUpsert)) *SystemSettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SystemSettingsUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SystemSettingsUpsertOne) SetUpdatedAt(v time.Time) *SystemSettingsUpsertOne {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SystemSettingsUpsertOne) UpdateUpdatedAt() *SystemSettingsUpsertOne {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SystemSettingsUpsertOne) SetDeletedAt(v int) *SystemSettingsUpsertOne {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *SystemSettingsUpsertOne) AddDeletedAt(v int) *SystemSettingsUpsertOne {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SystemSettingsUpsertOne) UpdateDeletedAt() *SystemSettingsUpsertOne {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetKey sets the "key" field.
func (u *SystemSettingsUpsertOne) SetKey(v string) *SystemSettingsUpsertOne {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *SystemSettingsUpsertOne) UpdateKey() *SystemSettingsUpsertOne {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.UpdateKey()
	})
}

// SetValue sets the "value" field.
func (u *SystemSettingsUpsertOne) SetValue(v map[string]interface{}) *SystemSettingsUpsertOne {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SystemSettingsUpsertOne) UpdateValue() *SystemSettingsUpsertOne {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.UpdateValue()
	})
}

// SetDescription sets the "description" field.
func (u *SystemSettingsUpsertOne) SetDescription(v string) *SystemSettingsUpsertOne {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SystemSettingsUpsertOne) UpdateDescription() *SystemSettingsUpsertOne {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SystemSettingsUpsertOne) ClearDescription() *SystemSettingsUpsertOne {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *SystemSettingsUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SystemSettingsCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SystemSettingsUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SystemSettingsUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SystemSettingsUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SystemSettingsCreateBulk is the builder for creating many SystemSettings entities in bulk.
type SystemSettingsCreateBulk struct {
	config
	err      error
	builders []*SystemSettingsCreate
	conflict []sql.ConflictOption
}

// Save creates the SystemSettings entities in the database.
func (_c *SystemSettingsCreateBulk) Save(ctx context.Context) ([]*SystemSettings, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SystemSettings, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SystemSettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SystemSettingsCreateBulk) SaveX(ctx context.Context) []*SystemSettings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SystemSettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SystemSettingsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SystemSettings.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SystemSettingsUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SystemSettingsCreateBulk) OnConflict(opts ...sql.ConflictOption) *SystemSettingsUpsertBulk {
	_c.conflict = opts
	return &SystemSettingsUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SystemSettings.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SystemSettingsCreateBulk) OnConflictColumns(columns ...string) *SystemSettingsUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SystemSettingsUpsertBulk{
		create: _c,
	}
}

// SystemSettingsUpsertBulk is the builder for "upsert"-ing
// a bulk of SystemSettings nodes.
type SystemSettingsUpsertBulk struct {
	create *SystemSettingsCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SystemSettings.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SystemSettingsUpsertBulk) UpdateNewValues() *SystemSettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(systemsettings.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SystemSettings.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SystemSettingsUpsertBulk) Ignore() *SystemSettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SystemSettingsUpsertBulk) DoNothing() *SystemSettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SystemSettingsCreateBulk.OnConflict
// documentation for more info.
func (u *SystemSettingsUpsertBulk) Update(set func(*SystemSettingsUpsert)) *SystemSettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SystemSettingsUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SystemSettingsUpsertBulk) SetUpdatedAt(v time.Time) *SystemSettingsUpsertBulk {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SystemSettingsUpsertBulk) UpdateUpdatedAt() *SystemSettingsUpsertBulk {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SystemSettingsUpsertBulk) SetDeletedAt(v int) *SystemSettingsUpsertBulk {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *SystemSettingsUpsertBulk) AddDeletedAt(v int) *SystemSettingsUpsertBulk {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SystemSettingsUpsertBulk) UpdateDeletedAt() *SystemSettingsUpsertBulk {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetKey sets the "key" field.
func (u *SystemSettingsUpsertBulk) SetKey(v string) *SystemSettingsUpsertBulk {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.SetKey(v)
	})
}

// UpdateKey sets the "key" field to the value that was provided on create.
func (u *SystemSettingsUpsertBulk) UpdateKey() *SystemSettingsUpsertBulk {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.UpdateKey()
	})
}

// SetValue sets the "value" field.
func (u *SystemSettingsUpsertBulk) SetValue(v map[string]interface{}) *SystemSettingsUpsertBulk {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *SystemSettingsUpsertBulk) UpdateValue() *SystemSettingsUpsertBulk {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.UpdateValue()
	})
}

// SetDescription sets the "description" field.
func (u *SystemSettingsUpsertBulk) SetDescription(v string) *SystemSettingsUpsertBulk {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SystemSettingsUpsertBulk) UpdateDescription() *SystemSettingsUpsertBulk {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SystemSettingsUpsertBulk) ClearDescription() *SystemSettingsUpsertBulk {
	return u.Update(func(s *SystemSettingsUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *SystemSettingsUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SystemSettingsCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SystemSettingsCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SystemSettingsUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
