package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/looplj/axonhub/internal/contexts"
	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/ent/apikey"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/ent/request"
	"github.com/looplj/axonhub/internal/ent/user"
	"github.com/looplj/axonhub/internal/objects"
	"github.com/looplj/axonhub/internal/scopes"
	"github.com/looplj/axonhub/internal/server/biz"
	"github.com/looplj/axonhub/llm/httpclient"
	"github.com/samber/lo"
)

// AllModelEntries is the resolver for the allModelEntries field.
func (r *channelResolver) AllModelEntries(ctx context.Context, obj *ent.Channel) ([]*biz.ChannelModelEntry, error) {
	ch := biz.Channel{Channel: obj}
	entries := ch.GetModelEntries()
	result := lo.Values(entries)

	return lo.ToSlicePtr(result), nil
}

// Credentials is the resolver for the credentials field.
func (r *channelResolver) Credentials(ctx context.Context, obj *ent.Channel) (*objects.ChannelCredentials, error) {
	hasScope := scopes.UserHasScope(ctx, scopes.ScopeWriteChannels)
	if hasScope {
		return obj.Credentials, nil
	}

	return nil, nil
}

// CreateChannel is the resolver for the createChannel field.
func (r *mutationResolver) CreateChannel(ctx context.Context, input ent.CreateChannelInput) (*ent.Channel, error) {
	return r.channelService.CreateChannel(ctx, input)
}

// BulkCreateChannels is the resolver for the bulkCreateChannels field.
func (r *mutationResolver) BulkCreateChannels(ctx context.Context, input biz.BulkCreateChannelsInput) ([]*ent.Channel, error) {
	return r.channelService.BulkCreateChannels(ctx, input)
}

// UpdateChannel is the resolver for the updateChannel field.
func (r *mutationResolver) UpdateChannel(ctx context.Context, id objects.GUID, input ent.UpdateChannelInput) (*ent.Channel, error) {
	return r.channelService.UpdateChannel(ctx, id.ID, &input)
}

// UpdateChannelStatus is the resolver for the updateChannelStatus field.
func (r *mutationResolver) UpdateChannelStatus(ctx context.Context, id objects.GUID, status channel.Status) (*ent.Channel, error) {
	return r.channelService.UpdateChannelStatus(ctx, id.ID, status)
}

// DeleteChannel is the resolver for the deleteChannel field.
func (r *mutationResolver) DeleteChannel(ctx context.Context, id objects.GUID) (bool, error) {
	if err := r.channelService.DeleteChannel(ctx, id.ID); err != nil {
		return false, err
	}

	return true, nil
}

// BulkArchiveChannels is the resolver for the bulkArchiveChannels field.
func (r *mutationResolver) BulkArchiveChannels(ctx context.Context, ids []*objects.GUID) (bool, error) {
	channelIDs := objects.IntGuids(ids)

	if err := r.channelService.BulkArchiveChannels(ctx, channelIDs); err != nil {
		return false, err
	}

	return true, nil
}

// BulkDisableChannels is the resolver for the bulkDisableChannels field.
func (r *mutationResolver) BulkDisableChannels(ctx context.Context, ids []*objects.GUID) (bool, error) {
	channelIDs := objects.IntGuids(ids)

	if err := r.channelService.BulkDisableChannels(ctx, channelIDs); err != nil {
		return false, err
	}

	return true, nil
}

// BulkEnableChannels is the resolver for the bulkEnableChannels field.
func (r *mutationResolver) BulkEnableChannels(ctx context.Context, ids []*objects.GUID) (bool, error) {
	channelIDs := objects.IntGuids(ids)

	if err := r.channelService.BulkEnableChannels(ctx, channelIDs); err != nil {
		return false, err
	}

	return true, nil
}

// BulkDeleteChannels is the resolver for the bulkDeleteChannels field.
func (r *mutationResolver) BulkDeleteChannels(ctx context.Context, ids []*objects.GUID) (bool, error) {
	channelIDs := objects.IntGuids(ids)

	if err := r.channelService.BulkDeleteChannels(ctx, channelIDs); err != nil {
		return false, err
	}

	return true, nil
}

// TestChannel is the resolver for the testChannel field.
func (r *mutationResolver) TestChannel(ctx context.Context, input TestChannelInput) (*TestChannelPayload, error) {
	// Set test source context for test channel requests
	ctx = contexts.WithSource(ctx, request.SourceTest)

	result, err := r.TestChannelOrchestrator.TestChannel(ctx, input.ChannelID, input.ModelID, input.Proxy)
	if err != nil {
		if httpclient.IsNotFoundErr(err) {
			return nil, fmt.Errorf("URL not found, please check if the URL is correct and try again")
		}

		return nil, fmt.Errorf("failed to test channel: %w", err)
	}

	return &TestChannelPayload{
		Latency: result.Latency,
		Success: result.Success,
		Error:   result.Error,
	}, nil
}

// BulkImportChannels is the resolver for the bulkImportChannels field.
func (r *mutationResolver) BulkImportChannels(ctx context.Context, input BulkImportChannelsInput) (*biz.BulkImportChannelsResult, error) {
	result, err := r.channelService.BulkImportChannels(ctx, input.Channels)
	if err != nil {
		return nil, err
	}

	return &biz.BulkImportChannelsResult{
		Success:  result.Success,
		Created:  result.Created,
		Failed:   result.Failed,
		Errors:   result.Errors,
		Channels: result.Channels,
	}, nil
}

// BulkUpdateChannelOrdering is the resolver for the bulkUpdateChannelOrdering field.
func (r *mutationResolver) BulkUpdateChannelOrdering(ctx context.Context, input BulkUpdateChannelOrderingInput) (*BulkUpdateChannelOrderingResult, error) {
	updatedChannels, err := r.channelService.BulkUpdateChannelOrdering(ctx, input.Channels)
	if err != nil {
		return nil, fmt.Errorf("failed to bulk update channel ordering: %w", err)
	}

	return &BulkUpdateChannelOrderingResult{
		Success:  true,
		Updated:  len(updatedChannels),
		Channels: updatedChannels,
	}, nil
}

// CreateAPIKey is the resolver for the createAPIKey field.
func (r *mutationResolver) CreateAPIKey(ctx context.Context, input ent.CreateAPIKeyInput) (*ent.APIKey, error) {
	return r.apiKeyService.CreateAPIKey(ctx, input)
}

// UpdateAPIKey is the resolver for the updateAPIKey field.
func (r *mutationResolver) UpdateAPIKey(ctx context.Context, id objects.GUID, input ent.UpdateAPIKeyInput) (*ent.APIKey, error) {
	return r.apiKeyService.UpdateAPIKey(ctx, id.ID, input)
}

// UpdateAPIKeyStatus is the resolver for the updateAPIKeyStatus field.
func (r *mutationResolver) UpdateAPIKeyStatus(ctx context.Context, id objects.GUID, status apikey.Status) (*ent.APIKey, error) {
	return r.apiKeyService.UpdateAPIKeyStatus(ctx, id.ID, status)
}

// UpdateAPIKeyProfiles is the resolver for the updateAPIKeyProfiles field.
func (r *mutationResolver) UpdateAPIKeyProfiles(ctx context.Context, id objects.GUID, input objects.APIKeyProfiles) (*ent.APIKey, error) {
	return r.apiKeyService.UpdateAPIKeyProfiles(ctx, id.ID, input)
}

// BulkDisableAPIKeys is the resolver for the bulkDisableAPIKeys field.
func (r *mutationResolver) BulkDisableAPIKeys(ctx context.Context, ids []*objects.GUID) (bool, error) {
	apiKeyIDs := objects.IntGuids(ids)

	err := r.apiKeyService.BulkDisableAPIKeys(ctx, apiKeyIDs)
	if err != nil {
		return false, err
	}

	return true, nil
}

// BulkEnableAPIKeys is the resolver for the bulkEnableAPIKeys field.
func (r *mutationResolver) BulkEnableAPIKeys(ctx context.Context, ids []*objects.GUID) (bool, error) {
	apiKeyIDs := objects.IntGuids(ids)

	err := r.apiKeyService.BulkEnableAPIKeys(ctx, apiKeyIDs)
	if err != nil {
		return false, err
	}

	return true, nil
}

// BulkArchiveAPIKeys is the resolver for the bulkArchiveAPIKeys field.
func (r *mutationResolver) BulkArchiveAPIKeys(ctx context.Context, ids []*objects.GUID) (bool, error) {
	apiKeyIDs := objects.IntGuids(ids)

	err := r.apiKeyService.BulkArchiveAPIKeys(ctx, apiKeyIDs)
	if err != nil {
		return false, err
	}

	return true, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input ent.CreateUserInput) (*ent.User, error) {
	return r.userService.CreateUser(ctx, input)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id objects.GUID, input ent.UpdateUserInput) (*ent.User, error) {
	return r.userService.UpdateUser(ctx, id.ID, input)
}

// UpdateUserStatus is the resolver for the updateUserStatus field.
func (r *mutationResolver) UpdateUserStatus(ctx context.Context, id objects.GUID, status user.Status) (*ent.User, error) {
	return r.userService.UpdateUserStatus(ctx, id.ID, status)
}

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, input ent.CreateRoleInput) (*ent.Role, error) {
	return r.roleService.CreateRole(ctx, input)
}

// UpdateRole is the resolver for the updateRole field.
func (r *mutationResolver) UpdateRole(ctx context.Context, id objects.GUID, input ent.UpdateRoleInput) (*ent.Role, error) {
	return r.roleService.UpdateRole(ctx, id.ID, input)
}

// DeleteRole is the resolver for the deleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, id objects.GUID) (bool, error) {
	err := r.roleService.DeleteRole(ctx, id.ID)
	if err != nil {
		return false, err
	}

	return true, nil
}

// BulkDeleteRoles is the resolver for the bulkDeleteRoles field.
func (r *mutationResolver) BulkDeleteRoles(ctx context.Context, ids []*objects.GUID) (bool, error) {
	roleIDs := objects.IntGuids(ids)

	err := r.roleService.BulkDeleteRoles(ctx, roleIDs)
	if err != nil {
		return false, err
	}

	return true, nil
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input ent.CreateProjectInput) (*ent.Project, error) {
	return r.projectService.CreateProject(ctx, input)
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id objects.GUID, input ent.UpdateProjectInput) (*ent.Project, error) {
	return r.projectService.UpdateProject(ctx, id.ID, input)
}

// UpdateProjectStatus is the resolver for the updateProjectStatus field.
func (r *mutationResolver) UpdateProjectStatus(ctx context.Context, id objects.GUID, status project.Status) (*ent.Project, error) {
	return r.projectService.UpdateProjectStatus(ctx, id.ID, status)
}

// AddUserToProject is the resolver for the addUserToProject field.
func (r *mutationResolver) AddUserToProject(ctx context.Context, input AddUserToProjectInput) (*ent.UserProject, error) {
	roleIDs := objects.IntGuids(input.RoleIDs)
	return r.userService.AddUserToProject(ctx, input.UserID.ID, input.ProjectID.ID, input.IsOwner, input.Scopes, roleIDs)
}

// RemoveUserFromProject is the resolver for the removeUserFromProject field.
func (r *mutationResolver) RemoveUserFromProject(ctx context.Context, input RemoveUserFromProjectInput) (bool, error) {
	err := r.userService.RemoveUserFromProject(ctx, input.UserID.ID, input.ProjectID.ID)
	if err != nil {
		return false, err
	}

	return true, nil
}

// UpdateProjectUser is the resolver for the updateProjectUser field.
func (r *mutationResolver) UpdateProjectUser(ctx context.Context, input UpdateProjectUserInput) (*ent.UserProject, error) {
	addRoleIDs := objects.IntGuids(input.AddRoleIDs)
	removeRoleIDs := objects.IntGuids(input.RemoveRoleIDs)

	return r.userService.UpdateProjectUser(ctx, input.UserID.ID, input.ProjectID.ID, input.IsOwner, input.Scopes, addRoleIDs, removeRoleIDs)
}

// CreateDataStorage is the resolver for the createDataStorage field.
func (r *mutationResolver) CreateDataStorage(ctx context.Context, input ent.CreateDataStorageInput) (*ent.DataStorage, error) {
	return r.dataStorageService.CreateDataStorage(ctx, &input)
}

// UpdateDataStorage is the resolver for the updateDataStorage field.
func (r *mutationResolver) UpdateDataStorage(ctx context.Context, id objects.GUID, input ent.UpdateDataStorageInput) (*ent.DataStorage, error) {
	return r.dataStorageService.UpdateDataStorage(ctx, id.ID, &input)
}

// CreateChannelOverrideTemplate is the resolver for the createChannelOverrideTemplate field.
func (r *mutationResolver) CreateChannelOverrideTemplate(ctx context.Context, input ent.CreateChannelOverrideTemplateInput) (*ent.ChannelOverrideTemplate, error) {
	user, ok := contexts.GetUser(ctx)
	if !ok {
		return nil, fmt.Errorf("user not found in context")
	}

	return r.channelOverrideTemplateService.CreateTemplate(ctx, user.ID, input)
}

// UpdateChannelOverrideTemplate is the resolver for the updateChannelOverrideTemplate field.
func (r *mutationResolver) UpdateChannelOverrideTemplate(ctx context.Context, id objects.GUID, input ent.UpdateChannelOverrideTemplateInput) (*ent.ChannelOverrideTemplate, error) {
	return r.channelOverrideTemplateService.UpdateTemplate(ctx, id.ID, input)
}

// DeleteChannelOverrideTemplate is the resolver for the deleteChannelOverrideTemplate field.
func (r *mutationResolver) DeleteChannelOverrideTemplate(ctx context.Context, id objects.GUID) (bool, error) {
	if err := r.channelOverrideTemplateService.DeleteTemplate(ctx, id.ID); err != nil {
		return false, err
	}

	return true, nil
}

// ApplyChannelOverrideTemplate is the resolver for the applyChannelOverrideTemplate field.
func (r *mutationResolver) ApplyChannelOverrideTemplate(ctx context.Context, input ApplyChannelOverrideTemplateInput) (*ApplyChannelOverrideTemplatePayload, error) {
	channelIDs := objects.IntGuids(input.ChannelIDs)

	updatedChannels, err := r.channelOverrideTemplateService.ApplyTemplate(
		ctx,
		input.TemplateID.ID,
		channelIDs,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to apply template: %w", err)
	}

	return &ApplyChannelOverrideTemplatePayload{
		Success:  true,
		Updated:  len(updatedChannels),
		Channels: updatedChannels,
	}, nil
}

// AllChannelTags is the resolver for the allChannelTags field.
func (r *queryResolver) AllChannelTags(ctx context.Context) ([]string, error) {
	// Query all channels that are not archived
	channels, err := r.client.Channel.
		Query().
		Select(channel.FieldTags).
		Where(channel.StatusNEQ(channel.StatusArchived)).
		All(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to query channels: %w", err)
	}

	tags := lo.Reduce(channels, func(acc []string, ch *ent.Channel, _ int) []string {
		return append(acc, ch.Tags...)
	}, []string{})

	return lo.Uniq(tags), nil
}

// CountChannelsByType is the resolver for the countChannelsByType field.
func (r *queryResolver) CountChannelsByType(ctx context.Context, input CountChannelsByTypeInput) ([]*ChannelTypeCount, error) {
	// Query channel types with counts
	var results []struct {
		Type  string `json:"type"`
		Count int    `json:"count"`
	}

	q := r.client.Channel.Query()
	if len(input.StatusIn) > 0 {
		q = q.Where(channel.StatusIn(input.StatusIn...))
	} else {
		q = q.Where(channel.StatusNEQ(channel.StatusArchived))
	}

	err := q.GroupBy(channel.FieldType).
		Aggregate(ent.Count()).Scan(ctx, &results)
	if err != nil {
		return nil, fmt.Errorf("failed to query channel type counts: %w", err)
	}

	typeCounts := make([]*ChannelTypeCount, len(results))
	for i, result := range results {
		typeCounts[i] = &ChannelTypeCount{
			Type:  result.Type,
			Count: result.Count,
		}
	}

	return typeCounts, nil
}

// QueryChannels is the resolver for the queryChannels field.
func (r *queryResolver) QueryChannels(ctx context.Context, input biz.QueryChannelsInput) (*ent.ChannelConnection, error) {
	if input.OrderBy != nil && input.OrderBy.Field.String() == "CREATED_AT" {
		input.OrderBy.Field = ent.DefaultChannelOrder.Field
	}
	return r.channelService.QueryChannels(ctx, input)
}

// QueryChannelOverrideTemplates is the resolver for the queryChannelOverrideTemplates field.
func (r *queryResolver) QueryChannelOverrideTemplates(ctx context.Context, input biz.QueryChannelOverrideTemplatesInput) (*ent.ChannelOverrideTemplateConnection, error) {
	if err := validatePaginationArgs(input.First, input.Last); err != nil {
		return nil, err
	}

	bizInput := biz.QueryChannelOverrideTemplatesInput{
		After:       input.After,
		First:       input.First,
		Before:      input.Before,
		Last:        input.Last,
		ChannelType: input.ChannelType,
		Search:      input.Search,
	}

	return r.channelOverrideTemplateService.QueryTemplates(ctx, bizInput)
}

// Cost is the resolver for the cost field.
func (r *requestResolver) Cost(ctx context.Context, obj *ent.Request) (*int, error) {
	if obj.TraceID == 0 {
		return nil, nil
	}

	if obj.Edges.Trace != nil {
		cost := int(obj.Edges.Trace.Cost)
		return &cost, nil
	}

	traceEntry, err := r.client.Trace.Get(ctx, obj.TraceID)
	if err != nil {
		if ent.IsNotFound(err) {
			return nil, nil
		}
		return nil, err
	}

	cost := int(traceEntry.Cost)
	return &cost, nil
}

// ID is the resolver for the id field.
func (r *segmentResolver) ID(ctx context.Context, obj *biz.Segment) (*objects.GUID, error) {
	return &objects.GUID{Type: ent.TypeRequest, ID: obj.ID}, nil
}

// ParentID is the resolver for the parentId field.
func (r *segmentResolver) ParentID(ctx context.Context, obj *biz.Segment) (*objects.GUID, error) {
	if obj.ParentID == nil {
		return nil, nil
	}

	return &objects.GUID{Type: ent.TypeRequest, ID: *obj.ParentID}, nil
}

// FirstUserQuery is the resolver for the firstUserQuery field.
func (r *threadResolver) FirstUserQuery(ctx context.Context, obj *ent.Thread) (*string, error) {
	return r.threadService.FirstUserQuery(ctx, obj.ID)
}

// UsageMetadata is the resolver for the usageMetadata field.
func (r *threadResolver) UsageMetadata(ctx context.Context, obj *ent.Thread) (*biz.UsageMetadata, error) {
	return r.threadService.UsageMetadata(ctx, obj.ID)
}

// RootSegment is the resolver for the rootSegment field.
func (r *traceResolver) RootSegment(ctx context.Context, obj *ent.Trace) (*biz.Segment, error) {
	return r.traceService.GetRootSegment(ctx, obj.ID)
}

// RawRootSegment is the resolver for the rawRootSegment field.
func (r *traceResolver) RawRootSegment(ctx context.Context, obj *ent.Trace) (objects.JSONRawMessage, error) {
	segment, err := r.traceService.GetRootSegment(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	data, err := json.Marshal(segment)
	if err != nil {
		return nil, err
	}

	return objects.JSONRawMessage(data), nil
}

// FirstUserQuery is the resolver for the firstUserQuery field.
func (r *traceResolver) FirstUserQuery(ctx context.Context, obj *ent.Trace) (*string, error) {
	return r.traceService.FirstUserQuery(ctx, obj.ID)
}

// FirstText is the resolver for the firstText field.
func (r *traceResolver) FirstText(ctx context.Context, obj *ent.Trace) (*string, error) {
	return r.traceService.FirstText(ctx, obj.ID)
}

// UsageMetadata is the resolver for the usageMetadata field.
func (r *traceResolver) UsageMetadata(ctx context.Context, obj *ent.Trace) (*biz.UsageMetadata, error) {
	return r.traceService.UsageMetadata(ctx, obj.ID)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Segment returns SegmentResolver implementation.
func (r *Resolver) Segment() SegmentResolver { return &segmentResolver{r} }

type mutationResolver struct{ *Resolver }
type segmentResolver struct{ *Resolver }
