// Code generated by ent, DO NOT EDIT.

package modelpricing

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldDeletedAt, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldModel, v))
}

// Quota applies equality check predicate on the "quota" field. It's identical to QuotaEQ.
func Quota(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldQuota, v))
}

// CompletionRatio applies equality check predicate on the "completion_ratio" field. It's identical to CompletionRatioEQ.
func CompletionRatio(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldCompletionRatio, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldPrice, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLTE(FieldDeletedAt, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldContainsFold(FieldModel, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v Type) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v Type) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...Type) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...Type) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldStatus, vs...))
}

// QuotaEQ applies the EQ predicate on the "quota" field.
func QuotaEQ(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldQuota, v))
}

// QuotaNEQ applies the NEQ predicate on the "quota" field.
func QuotaNEQ(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldQuota, v))
}

// QuotaIn applies the In predicate on the "quota" field.
func QuotaIn(vs ...float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldQuota, vs...))
}

// QuotaNotIn applies the NotIn predicate on the "quota" field.
func QuotaNotIn(vs ...float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldQuota, vs...))
}

// QuotaGT applies the GT predicate on the "quota" field.
func QuotaGT(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGT(FieldQuota, v))
}

// QuotaGTE applies the GTE predicate on the "quota" field.
func QuotaGTE(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGTE(FieldQuota, v))
}

// QuotaLT applies the LT predicate on the "quota" field.
func QuotaLT(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLT(FieldQuota, v))
}

// QuotaLTE applies the LTE predicate on the "quota" field.
func QuotaLTE(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLTE(FieldQuota, v))
}

// CompletionRatioEQ applies the EQ predicate on the "completion_ratio" field.
func CompletionRatioEQ(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldCompletionRatio, v))
}

// CompletionRatioNEQ applies the NEQ predicate on the "completion_ratio" field.
func CompletionRatioNEQ(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldCompletionRatio, v))
}

// CompletionRatioIn applies the In predicate on the "completion_ratio" field.
func CompletionRatioIn(vs ...float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldCompletionRatio, vs...))
}

// CompletionRatioNotIn applies the NotIn predicate on the "completion_ratio" field.
func CompletionRatioNotIn(vs ...float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldCompletionRatio, vs...))
}

// CompletionRatioGT applies the GT predicate on the "completion_ratio" field.
func CompletionRatioGT(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGT(FieldCompletionRatio, v))
}

// CompletionRatioGTE applies the GTE predicate on the "completion_ratio" field.
func CompletionRatioGTE(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGTE(FieldCompletionRatio, v))
}

// CompletionRatioLT applies the LT predicate on the "completion_ratio" field.
func CompletionRatioLT(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLT(FieldCompletionRatio, v))
}

// CompletionRatioLTE applies the LTE predicate on the "completion_ratio" field.
func CompletionRatioLTE(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLTE(FieldCompletionRatio, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.ModelPricing {
	return predicate.ModelPricing(sql.FieldLTE(FieldPrice, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelPricing) predicate.ModelPricing {
	return predicate.ModelPricing(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelPricing) predicate.ModelPricing {
	return predicate.ModelPricing(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelPricing) predicate.ModelPricing {
	return predicate.ModelPricing(sql.NotPredicates(p))
}
