// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent"
	"github.com/looplj/axonhub/internal/ent/apikey"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/channeloverridetemplate"
	"github.com/looplj/axonhub/internal/ent/channelperformance"
	"github.com/looplj/axonhub/internal/ent/consumptionrecord"
	"github.com/looplj/axonhub/internal/ent/datastorage"
	"github.com/looplj/axonhub/internal/ent/model"
	"github.com/looplj/axonhub/internal/ent/modelpricing"
	"github.com/looplj/axonhub/internal/ent/predicate"
	"github.com/looplj/axonhub/internal/ent/project"
	"github.com/looplj/axonhub/internal/ent/rechargerecord"
	"github.com/looplj/axonhub/internal/ent/redemptioncode"
	"github.com/looplj/axonhub/internal/ent/request"
	"github.com/looplj/axonhub/internal/ent/requestexecution"
	"github.com/looplj/axonhub/internal/ent/role"
	"github.com/looplj/axonhub/internal/ent/sensitiveword"
	"github.com/looplj/axonhub/internal/ent/system"
	"github.com/looplj/axonhub/internal/ent/systemsettings"
	"github.com/looplj/axonhub/internal/ent/thread"
	"github.com/looplj/axonhub/internal/ent/trace"
	"github.com/looplj/axonhub/internal/ent/usagelog"
	"github.com/looplj/axonhub/internal/ent/user"
	"github.com/looplj/axonhub/internal/ent/userproject"
	"github.com/looplj/axonhub/internal/ent/userrole"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next ent.Querier) ent.Querier {
	return ent.QuerierFunc(func(ctx context.Context, q ent.Query) (ent.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q ent.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The APIKeyFunc type is an adapter to allow the use of ordinary function as a Querier.
type APIKeyFunc func(context.Context, *ent.APIKeyQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f APIKeyFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.APIKeyQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.APIKeyQuery", q)
}

// The TraverseAPIKey type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAPIKey func(context.Context, *ent.APIKeyQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAPIKey) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAPIKey) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.APIKeyQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.APIKeyQuery", q)
}

// The ChannelFunc type is an adapter to allow the use of ordinary function as a Querier.
type ChannelFunc func(context.Context, *ent.ChannelQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ChannelFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ChannelQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ChannelQuery", q)
}

// The TraverseChannel type is an adapter to allow the use of ordinary function as Traverser.
type TraverseChannel func(context.Context, *ent.ChannelQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseChannel) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseChannel) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ChannelQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ChannelQuery", q)
}

// The ChannelOverrideTemplateFunc type is an adapter to allow the use of ordinary function as a Querier.
type ChannelOverrideTemplateFunc func(context.Context, *ent.ChannelOverrideTemplateQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ChannelOverrideTemplateFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ChannelOverrideTemplateQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ChannelOverrideTemplateQuery", q)
}

// The TraverseChannelOverrideTemplate type is an adapter to allow the use of ordinary function as Traverser.
type TraverseChannelOverrideTemplate func(context.Context, *ent.ChannelOverrideTemplateQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseChannelOverrideTemplate) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseChannelOverrideTemplate) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ChannelOverrideTemplateQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ChannelOverrideTemplateQuery", q)
}

// The ChannelPerformanceFunc type is an adapter to allow the use of ordinary function as a Querier.
type ChannelPerformanceFunc func(context.Context, *ent.ChannelPerformanceQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ChannelPerformanceFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ChannelPerformanceQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ChannelPerformanceQuery", q)
}

// The TraverseChannelPerformance type is an adapter to allow the use of ordinary function as Traverser.
type TraverseChannelPerformance func(context.Context, *ent.ChannelPerformanceQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseChannelPerformance) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseChannelPerformance) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ChannelPerformanceQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ChannelPerformanceQuery", q)
}

// The ConsumptionRecordFunc type is an adapter to allow the use of ordinary function as a Querier.
type ConsumptionRecordFunc func(context.Context, *ent.ConsumptionRecordQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ConsumptionRecordFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ConsumptionRecordQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ConsumptionRecordQuery", q)
}

// The TraverseConsumptionRecord type is an adapter to allow the use of ordinary function as Traverser.
type TraverseConsumptionRecord func(context.Context, *ent.ConsumptionRecordQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseConsumptionRecord) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseConsumptionRecord) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ConsumptionRecordQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ConsumptionRecordQuery", q)
}

// The DataStorageFunc type is an adapter to allow the use of ordinary function as a Querier.
type DataStorageFunc func(context.Context, *ent.DataStorageQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f DataStorageFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.DataStorageQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.DataStorageQuery", q)
}

// The TraverseDataStorage type is an adapter to allow the use of ordinary function as Traverser.
type TraverseDataStorage func(context.Context, *ent.DataStorageQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseDataStorage) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseDataStorage) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.DataStorageQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.DataStorageQuery", q)
}

// The ModelFunc type is an adapter to allow the use of ordinary function as a Querier.
type ModelFunc func(context.Context, *ent.ModelQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ModelFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ModelQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ModelQuery", q)
}

// The TraverseModel type is an adapter to allow the use of ordinary function as Traverser.
type TraverseModel func(context.Context, *ent.ModelQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseModel) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseModel) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ModelQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ModelQuery", q)
}

// The ModelPricingFunc type is an adapter to allow the use of ordinary function as a Querier.
type ModelPricingFunc func(context.Context, *ent.ModelPricingQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ModelPricingFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ModelPricingQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ModelPricingQuery", q)
}

// The TraverseModelPricing type is an adapter to allow the use of ordinary function as Traverser.
type TraverseModelPricing func(context.Context, *ent.ModelPricingQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseModelPricing) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseModelPricing) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ModelPricingQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ModelPricingQuery", q)
}

// The ProjectFunc type is an adapter to allow the use of ordinary function as a Querier.
type ProjectFunc func(context.Context, *ent.ProjectQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ProjectFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ProjectQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ProjectQuery", q)
}

// The TraverseProject type is an adapter to allow the use of ordinary function as Traverser.
type TraverseProject func(context.Context, *ent.ProjectQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseProject) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseProject) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ProjectQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ProjectQuery", q)
}

// The RechargeRecordFunc type is an adapter to allow the use of ordinary function as a Querier.
type RechargeRecordFunc func(context.Context, *ent.RechargeRecordQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RechargeRecordFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RechargeRecordQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RechargeRecordQuery", q)
}

// The TraverseRechargeRecord type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRechargeRecord func(context.Context, *ent.RechargeRecordQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRechargeRecord) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRechargeRecord) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RechargeRecordQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RechargeRecordQuery", q)
}

// The RedemptionCodeFunc type is an adapter to allow the use of ordinary function as a Querier.
type RedemptionCodeFunc func(context.Context, *ent.RedemptionCodeQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RedemptionCodeFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RedemptionCodeQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RedemptionCodeQuery", q)
}

// The TraverseRedemptionCode type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRedemptionCode func(context.Context, *ent.RedemptionCodeQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRedemptionCode) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRedemptionCode) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RedemptionCodeQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RedemptionCodeQuery", q)
}

// The RequestFunc type is an adapter to allow the use of ordinary function as a Querier.
type RequestFunc func(context.Context, *ent.RequestQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RequestFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RequestQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RequestQuery", q)
}

// The TraverseRequest type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRequest func(context.Context, *ent.RequestQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRequest) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRequest) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RequestQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RequestQuery", q)
}

// The RequestExecutionFunc type is an adapter to allow the use of ordinary function as a Querier.
type RequestExecutionFunc func(context.Context, *ent.RequestExecutionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RequestExecutionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RequestExecutionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RequestExecutionQuery", q)
}

// The TraverseRequestExecution type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRequestExecution func(context.Context, *ent.RequestExecutionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRequestExecution) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRequestExecution) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RequestExecutionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RequestExecutionQuery", q)
}

// The RoleFunc type is an adapter to allow the use of ordinary function as a Querier.
type RoleFunc func(context.Context, *ent.RoleQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RoleFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RoleQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RoleQuery", q)
}

// The TraverseRole type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRole func(context.Context, *ent.RoleQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRole) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRole) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RoleQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RoleQuery", q)
}

// The SensitiveWordFunc type is an adapter to allow the use of ordinary function as a Querier.
type SensitiveWordFunc func(context.Context, *ent.SensitiveWordQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SensitiveWordFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SensitiveWordQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SensitiveWordQuery", q)
}

// The TraverseSensitiveWord type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSensitiveWord func(context.Context, *ent.SensitiveWordQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSensitiveWord) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSensitiveWord) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SensitiveWordQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SensitiveWordQuery", q)
}

// The SystemFunc type is an adapter to allow the use of ordinary function as a Querier.
type SystemFunc func(context.Context, *ent.SystemQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SystemFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SystemQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SystemQuery", q)
}

// The TraverseSystem type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSystem func(context.Context, *ent.SystemQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSystem) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSystem) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SystemQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SystemQuery", q)
}

// The SystemSettingsFunc type is an adapter to allow the use of ordinary function as a Querier.
type SystemSettingsFunc func(context.Context, *ent.SystemSettingsQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SystemSettingsFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SystemSettingsQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SystemSettingsQuery", q)
}

// The TraverseSystemSettings type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSystemSettings func(context.Context, *ent.SystemSettingsQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSystemSettings) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSystemSettings) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SystemSettingsQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SystemSettingsQuery", q)
}

// The ThreadFunc type is an adapter to allow the use of ordinary function as a Querier.
type ThreadFunc func(context.Context, *ent.ThreadQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ThreadFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ThreadQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ThreadQuery", q)
}

// The TraverseThread type is an adapter to allow the use of ordinary function as Traverser.
type TraverseThread func(context.Context, *ent.ThreadQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseThread) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseThread) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ThreadQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ThreadQuery", q)
}

// The TraceFunc type is an adapter to allow the use of ordinary function as a Querier.
type TraceFunc func(context.Context, *ent.TraceQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f TraceFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.TraceQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.TraceQuery", q)
}

// The TraverseTrace type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTrace func(context.Context, *ent.TraceQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTrace) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTrace) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.TraceQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.TraceQuery", q)
}

// The UsageLogFunc type is an adapter to allow the use of ordinary function as a Querier.
type UsageLogFunc func(context.Context, *ent.UsageLogQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UsageLogFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UsageLogQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UsageLogQuery", q)
}

// The TraverseUsageLog type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUsageLog func(context.Context, *ent.UsageLogQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUsageLog) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUsageLog) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UsageLogQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UsageLogQuery", q)
}

// The UserFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserFunc func(context.Context, *ent.UserQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// The TraverseUser type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUser func(context.Context, *ent.UserQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUser) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUser) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// The UserProjectFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserProjectFunc func(context.Context, *ent.UserProjectQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserProjectFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserProjectQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserProjectQuery", q)
}

// The TraverseUserProject type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserProject func(context.Context, *ent.UserProjectQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserProject) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserProject) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserProjectQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserProjectQuery", q)
}

// The UserRoleFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserRoleFunc func(context.Context, *ent.UserRoleQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserRoleFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserRoleQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserRoleQuery", q)
}

// The TraverseUserRole type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserRole func(context.Context, *ent.UserRoleQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserRole) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserRole) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserRoleQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserRoleQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q ent.Query) (Query, error) {
	switch q := q.(type) {
	case *ent.APIKeyQuery:
		return &query[*ent.APIKeyQuery, predicate.APIKey, apikey.OrderOption]{typ: ent.TypeAPIKey, tq: q}, nil
	case *ent.ChannelQuery:
		return &query[*ent.ChannelQuery, predicate.Channel, channel.OrderOption]{typ: ent.TypeChannel, tq: q}, nil
	case *ent.ChannelOverrideTemplateQuery:
		return &query[*ent.ChannelOverrideTemplateQuery, predicate.ChannelOverrideTemplate, channeloverridetemplate.OrderOption]{typ: ent.TypeChannelOverrideTemplate, tq: q}, nil
	case *ent.ChannelPerformanceQuery:
		return &query[*ent.ChannelPerformanceQuery, predicate.ChannelPerformance, channelperformance.OrderOption]{typ: ent.TypeChannelPerformance, tq: q}, nil
	case *ent.ConsumptionRecordQuery:
		return &query[*ent.ConsumptionRecordQuery, predicate.ConsumptionRecord, consumptionrecord.OrderOption]{typ: ent.TypeConsumptionRecord, tq: q}, nil
	case *ent.DataStorageQuery:
		return &query[*ent.DataStorageQuery, predicate.DataStorage, datastorage.OrderOption]{typ: ent.TypeDataStorage, tq: q}, nil
	case *ent.ModelQuery:
		return &query[*ent.ModelQuery, predicate.Model, model.OrderOption]{typ: ent.TypeModel, tq: q}, nil
	case *ent.ModelPricingQuery:
		return &query[*ent.ModelPricingQuery, predicate.ModelPricing, modelpricing.OrderOption]{typ: ent.TypeModelPricing, tq: q}, nil
	case *ent.ProjectQuery:
		return &query[*ent.ProjectQuery, predicate.Project, project.OrderOption]{typ: ent.TypeProject, tq: q}, nil
	case *ent.RechargeRecordQuery:
		return &query[*ent.RechargeRecordQuery, predicate.RechargeRecord, rechargerecord.OrderOption]{typ: ent.TypeRechargeRecord, tq: q}, nil
	case *ent.RedemptionCodeQuery:
		return &query[*ent.RedemptionCodeQuery, predicate.RedemptionCode, redemptioncode.OrderOption]{typ: ent.TypeRedemptionCode, tq: q}, nil
	case *ent.RequestQuery:
		return &query[*ent.RequestQuery, predicate.Request, request.OrderOption]{typ: ent.TypeRequest, tq: q}, nil
	case *ent.RequestExecutionQuery:
		return &query[*ent.RequestExecutionQuery, predicate.RequestExecution, requestexecution.OrderOption]{typ: ent.TypeRequestExecution, tq: q}, nil
	case *ent.RoleQuery:
		return &query[*ent.RoleQuery, predicate.Role, role.OrderOption]{typ: ent.TypeRole, tq: q}, nil
	case *ent.SensitiveWordQuery:
		return &query[*ent.SensitiveWordQuery, predicate.SensitiveWord, sensitiveword.OrderOption]{typ: ent.TypeSensitiveWord, tq: q}, nil
	case *ent.SystemQuery:
		return &query[*ent.SystemQuery, predicate.System, system.OrderOption]{typ: ent.TypeSystem, tq: q}, nil
	case *ent.SystemSettingsQuery:
		return &query[*ent.SystemSettingsQuery, predicate.SystemSettings, systemsettings.OrderOption]{typ: ent.TypeSystemSettings, tq: q}, nil
	case *ent.ThreadQuery:
		return &query[*ent.ThreadQuery, predicate.Thread, thread.OrderOption]{typ: ent.TypeThread, tq: q}, nil
	case *ent.TraceQuery:
		return &query[*ent.TraceQuery, predicate.Trace, trace.OrderOption]{typ: ent.TypeTrace, tq: q}, nil
	case *ent.UsageLogQuery:
		return &query[*ent.UsageLogQuery, predicate.UsageLog, usagelog.OrderOption]{typ: ent.TypeUsageLog, tq: q}, nil
	case *ent.UserQuery:
		return &query[*ent.UserQuery, predicate.User, user.OrderOption]{typ: ent.TypeUser, tq: q}, nil
	case *ent.UserProjectQuery:
		return &query[*ent.UserProjectQuery, predicate.UserProject, userproject.OrderOption]{typ: ent.TypeUserProject, tq: q}, nil
	case *ent.UserRoleQuery:
		return &query[*ent.UserRoleQuery, predicate.UserRole, userrole.OrderOption]{typ: ent.TypeUserRole, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
